### ISSUE TITLE
307 hours, etc.

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#139]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/3XX.csv

**Comment by cwarc** [comment]
https://docs.google.com/spreadsheets/d/18LxuVLsaZaEH4KdeVVOVqKyM0Sv2nAT6j1yrlIks1sk/edit#gid=1732665728

Hello Everyone,

Please see the first pass for 307 - Hours, Etc. (R). Would anyone like to take a look.

Best,
Alice

**Comment by pan-zhuo** [comment]
The current mapping "has note on item" requires minting an item entity. However, there is no holding information in this field. Coder would like to confirm if this is intended.

**Comment by CECSpecialistI** [comment]
@AdamSchiff what do you think? I've never seen a 307 in the wild. Do these usually have a $5 associated with them? Are they item information? It seems to be holdings information to me, which would make sense to include at the item level. Maybe we could map only if there is a $5 present so we're not minting extra items that are floating around unattached to holding institutions.

**Comment by CECSpecialistI** [comment]
@AdamSchiff I think I asked you this question while you were on vacation, apologies for that! Do you have any thoughts on whether these are item information and usually have a $5 associated with them?

**Comment by AdamSchiff** [comment]
I have NEVER seen an example of this field.  In fact, I don't think I ever was aware of its existence.  $5 is not defined in the field, so this information is applicable to any library and is not at the RDA item level.  It is intended only for electronic resources.  It was created in 2008, when I suppose there were times some online resources were offline at some regular pattern that could be recorded.  I can't imagine that this field was used much if at all by anyone. But I'd say it is manifestation information.

Postscript: I found OCLC usage statistics field by field in the Internet Archive's Wayback Machine: https://web.archive.org/web/20220816141130/http://experimental.worldcat.org/marcusage/

The latest info on 307 that I could find showed it used a lot more than I expected:

TOTAL Number of Records with this field:
822,929 out of a total of 411,948,429 MARC records as of 1 Jan 2018
[cid:5e7c0d16-324a-4280-bdc4-f14a3315e5dd]

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________

**Comment by CECSpecialistI** [comment]
Thanks Adam! Based on this, I've changed the mapping to note on manifestation and am marking it ready for transform.
