### ISSUE TITLE
337 media type

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#147]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/3XX.csv

**Comment by CECSpecialistI** [comment]
Decided during 2023-05-03 meeting we should examine values and re-evaluate mapping output to use RDA values whenever possible, and create map/alignment from RDA VES to id.loc VES and send to RSC to see if they will add to RDA Registry. @szapoun  will post National Library of Greece alignments, @GordonDunsire  will look at it

**Comment by szapoun** [comment]
NLG mapping for 337
[337.xlsx](https://github.com/uwlib-cams/MARC2RDA/files/11403554/337.xlsx)

**Comment by GordonDunsire** [comment]
I have checked the NLG alignment and don't see any errors.

For the purposes of an RDA to MARC 21 mapping, RDA prefers to use SKOS to relate RDA concepts, which are already expressed in SKOS, to external concepts.

The LC concepts are also expressed in SKOS, albeit alongside a MADS representation.

In all cases, I think the correct alignment and mapping is SKOS "close match".

The LC vocabulary and concepts appear to be a near copy of the RDA vocabulary, although it has additional, non-RDA concepts.

[RDAMT2M21NT.txt](https://github.com/uwlib-cams/MARC2RDA/files/11430916/RDAMT2M21NT.txt)

RDAMT2M21NT is an n-triples version of the map (in text format for GitHub purposes). The NT format is suitable for submitting the map to the RSC Technical Working Group for approval and publication in the RDA Registry.

Note: skos:closeMatch is effectively a symmetric property, so the map can be flipped and used to reverse-engineer M21 data that uses the M21 vocabulary.
