### ISSUE TITLE
342 geospatial reference data

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#151]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/3XX.csv

**Comment by CECSpecialistI** [comment]
@CatalogerCate, Penny and I have run into a question we hope you won't mind answering. Is there a difference between a prime meridian and a projection center? The context is [MARC 342](https://www.loc.gov/marc/bibliographic/bd342.html) $g and $h. Thank you in advance!

**Comment by CECSpecialistI** [comment]
Also, would resolution on a map be a work or expression characteristic? @CatalogerCate @GordonDunsire

**Comment by GordonDunsire** [comment]
@CECSpecialistI: I don't know much about map projections, but a prime meridian (or any line of longitude) is a line, and I assume a projection centre is a point that is specified by the intersection of the meridian with a line of latitude. They pertain to different types of map projection as specified in the MARC 21 manual.

I assume that, in general, resolution is an expression characteristic, with the work covering the area represented, features selected, etc. But I suspect for some specific cases the decision would be that a difference in resolution results in a new work. This is pretty much the same as for all kinds of works and expressions. This should not be confused with printing or display resolution (e.g. 200 dots per inch), which is a manifestation characteristic.

**Comment by pennylenger** [comment]
"Thank you very much, @GordonDunsire, for the explanation. Can we do better than note on expression for $c - Latitude resolution (NR), $d - Longitude resolution (NR), and $t - Vertical resolution (NR)?  
And I run into another question, for the second indicator, 7 - Method specified in $2, how can I address the mapping of 7 when it is combined with two first indicators and all subfields?" @CECSpecialistI @lake44me

**Comment by pennylenger** [comment]
@GordonDunsire @CECSpecialistI @lake44me There are many conditions in 342. I'd like to clarify these conditions for easy understanding, but not sure what approach I should take to explain these conditions. For example:

$g Longitude of central meridian or projection center
Longitude of the central meridian (the line of longitude at the center of a map projection, generally used as the basis for constructing the projection) when the second indicator contains the value 1 and subfield $a contains the text Albers conical equal area, Azimuthal equidistant, Equidistant conic, Equirectangular, Lambert conformal conic, Mercator, Miller cylindrical, Polyconic, Sinusoidal, Transverse Mercator, or Van der Grinten. Subfield $g contains a longitude of projection center (longitude of the point of projection for azimuthal projections) when the second indicator contains the value 1 and subfield $a contains the text General vertical near-sided projection, Gnomomic, Lambert azimuthal equal area, Orthographic, Robinson, or Stereographic.
342 | 01$aPolyconic$g0.9996$h0$i500,000$j0

$k - Scale factor
Used when the first indicator contains the value 1. If subfield $a contains the text Mercator, subfield $k contains the scale factor at equator (a multiplier for reducing a distance obtained from a map to the actual distance along the equator). If subfield $a contains Oblique Mercator, subfield $k contains the scale factor at center line (a multiplier for reducing a distance obtained from a map to the actual distance along the center line). If subfield $a contains Transverse Mercator, subfield $k contains the scale factor at central meridian (a multiplier for reducing a distance obtained from a map to the actual distance along the central meridian). If subfield $a contains Polar stereographic, subfield $k contains the scale factor at the projection origin (a multiplier for reducing a distance obtained from a map to the actual distance at the projection origin).
342 | 12$aUniversal Transverse Mercator$p13$k0.9996$g-105.00$h0.00$i500,000$j0.0

Could you please give me some advice or examples?

**Comment by CECSpecialistI** [comment]
Hi @pennylenger ! This is a complex field! Let's work through some of these conditions together on Thursday. It will be a good introduction to writing mapping conditions and will be easier than trying to explain with a comment.

**Comment by dchen077** [comment]
@pennylenger Hi Penny, just to clarify, for the transform note on $k and when $a contains "mercator", the condition should be "contains mercator AND not contains oblique mercator and transverse mercator"? I.e. $a universal transverse mercator should only have the text ”scale factor at central meridian“ and not ”scale factor at equator“?

**Comment by pennylenger** [comment]
Yes, you are right.
