### ISSUE TITLE
343 planar coordinate data

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#152]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/3XX.csv

**Comment by cwarc** [comment]
https://docs.google.com/spreadsheets/d/1k0d6FnQEW58-7UzKI8-AgorUX2dA8-_zg5sJAR1x0jk/edit#gid=987440556

Hello All,

I have attached the finished first pass for 343 - Planar Coordinate Data (R). Can someone do a review?

Thanks,
Alice
