### ISSUE TITLE
00-04

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#17]
Map [leader and directory spreadsheet](https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/LDR-DIR.csv)

**Comment by CECSpecialistI** [comment]
Transferring blanket issues for chunks of mapping to milestones so each MARC field can be its own (more manageable) issue

**Comment by sarahruska** [comment]
@CECSpecialistI @cspayne - I'm closing this issue since its status is Done. Feel free to reopen and change the status if this in a different state
