### ISSUE TITLE
504 bibliography, etc. note

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#183]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by cwarc** [comment]
https://docs.google.com/spreadsheets/d/1-SZonEgKgL37e8ObRccSAOc8iNDKXZnHhFswgrC_KxE/edit#gid=1681914867

Hello Everyone,

Please see the first pass of 504 - Bibliography, Etc. Note (R). Would someone be able to review it?

Thank you.

Best,
Alice
