### ISSUE TITLE
522 geographic coverage note

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#199]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by cwarc** [comment]
https://docs.google.com/spreadsheets/d/1Hd5Kwp7HOrqJfzUQYzwnrb8Q7cgzfCCJssM-KTq0ZAM/edit#gid=1293943126

Hello everyone,

Please see the first pass of 522 - Geographic Coverage Note (R). Would someone be able to take a look?

Best,
Alice

**Comment by lake44me** [comment]
Reviewed, moved to ready for transform
