### ISSUE TITLE
Control Subfields

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#20]
The control subfields in [Appendix A](https://www.loc.gov/marc/bibliographic/ecbdcntf.html) of the MARC Bibliographic Standard have made their first appearance at the end of the 490 field [here](https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/4XX.csv#L419). They're going to reappear all over this mapping, and they aren't included in the existing mapping the RSC published on the Registry. Should we add this appendix to another mapping spreadsheet in our Working Documents, deal with them there, and refer to that document as these fields appear in all the other spreadsheets? Does anyone have ideas about how these should be mapped?

**Comment by CECSpecialistI** [comment]
Should we map provenance information?

**Comment by AdamSchiff** [comment]
Much provenance info has no place to go in MARC. But some does.

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
Box 352900
Seattle, WA 98195-2900
aschiff @ uw.edu
________________________________

**Comment by pan-zhuo** [comment]
For $6, it seems easier if the field is a transcription field. It would mean a parallel metadata statement in a non-Latin script is needed. Then maybe just take the field tag in 880 $6 and treat it the same way we treat the associated regular field.

```
245 10$6880-01$a[Title in Latin script]
880 10$6245-01/(2/r$a[Title in Hebrew script linked to associated field]
```
Treat the 880 as a 245.
For script identification code, rdf language tags seem more specific.
For orientation code, may have to do with the [base direction](https://w3c.github.io/rdf-dir-literal/)? Doesn't seem to have been implemented at this time.

For identifiers, if the cataloging language is English, are there ever identifiers not expressed in Latin script?

Not sure about headings yet.

**Comment by AdamSchiff** [comment]
Most identifiers would be expressed in Latin script and Arabic numerals.  But it would be possible for some not to be.  I can't think of a real example within RDA yet, but to illustrate that an identifier doesn't have to be in Latin, here's a Wikidata property:

INPA park ID (https://www.wikidata.org/wiki/Property:P10392):


[cid:96bdb780-3241-42dd-864d-d7c520a36b24]

And here's one where some identifiers are in Chinese or a mix of Chinese and Latin script:

[cid:3bcf7de2-72a5-4d01-8f45-f6932abb5af7]

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________
