### ISSUE TITLE
527 censorship note [obsolete]

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#204]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by cwarc** [comment]
https://docs.google.com/spreadsheets/d/1r8d5PvsgvwHYELL4IJoAVaIloz-NGhdfU_ZNwFGESCc/edit#gid=545955088

Hello Everyone,

Please see the first pass for the spreadsheet for Field 527 - Censorship Note (VM) [OBSOLETE, 1990]. Would anyone like to review it?

Thanks.

Best,
Alice

**Comment by pan-zhuo** [comment]
Since ["has censor agent"](http://rdaregistry.info/Elements/e/P20287) is an Expression property, maybe "has note on expression" aligns more closely with it than "has note on work" (in most cases)?

**Comment by CECSpecialistI** [comment]
This makes sense to me, changing to "has note on expression" in spreadsheet
