### ISSUE TITLE
538 system details note

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#212]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by cspayne** [comment]
[We need to confirm decision on multiple $5s](https://github.com/uwlib-cams/MARC2RDA/discussions/361#discussioncomment-9972430)

**Comment by cspayne** [comment]
Decision in meeting 2024-07-17: We reviewed decision on $5. We will mint items for each $5, including multiple $5s in one field.
