### ISSUE TITLE
541 immediate source of acquisition note

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#214]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by pennylenger** [comment]
@CECSpecialistI I am mapping 541 - Immediate Source of Acquisition Note (R), and I find the element **has immediate source of acquisition of item** which can be used for all subfields: MARC 21 Bibliographic 541 ** $a, b, c, d, e, f, h, n, o [structured description]. Under recording a structured description, it says use a vocabulary encoding scheme as a source of information. Record the form found in the vocabulary encoding scheme. Do not amend the values or punctuation. How can I find a VES for this 541 tag and fill in the Transformation Notes?

**Comment by pennylenger** [comment]
@CECSpecialistI I see in the spreadsheet, there already list 20 RDA Registry Labels for subfield a Source of acquisition (NR). I wonder where they come from. And the first and second indicator are listed for subfield 3 5 6 8, but not for other subfields. Why subfields 3 5 6 8 need indicator seperately listing ?

**Comment by pennylenger** [comment]
I remember last time  subfields 3 5 6 8 are not mapped. I still don't understand why they are not mapped.

**Comment by AdamSchiff** [comment]
I think they aren't mapped because there are no RDA elements that cover them.

Adam


Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________

**Comment by CECSpecialistI** [comment]
Hi Penny,

Don't worry too much about the fields already present in mapping spreadsheets. They were generated programmatically using the RDA mapping in the other direction (RDA to MARC), which cannot be round-tripped and results in many incorrect mappings. Other rows were added programmatically to make sure no MARC fields or subfields were missing from the spreadsheets. The human review you are doing is the first, so pre-existing rows are bound to not make sense a lot of the time. 

We  have discussed transformation approaches to subfields 3, 5, 6, and 8 as they apply to all MARC fields already, so those don't need to be mapped in individual spreadsheets. Additionally, as Adam says, there aren't specific RDA properties to map them to anyhow.

For a string encoding scheme for the 541 note, and I hope others will correct me if I'm wrong, but note fields in MARC do not generally follow vocabulary encoding schemes and should usually be mapped as unstructured values. I think our best bet will be to map all the subfields, in a specified order and with punctuation added where it isn't included in the MARC, to a single unstructured value for "has immediate source of acquisition of item". @AdamSchiff @GordonDunsire @szapoun does this seem right to you?

**Comment by CECSpecialistI** [comment]
[Discussion on $3](https://github.com/uwlib-cams/MARC2RDA/discussions/353)<br>
[Discussion on $5](https://github.com/uwlib-cams/MARC2RDA/discussions/361)<br>
Not mapping $8 until a use case is provided. <br>
[Decision on $6](https://github.com/uwlib-cams/MARC2RDA/wiki/Decisions-Index#iig-6)

**Comment by pennylenger** [comment]
@CECSpecialistI As I reflect on this "(item - minted) has manifestation exemplified (manifestation the MARC is describing)
ex: manifestationIRI rdamo:p30103  ex:itemIRI "Source of acquisition: " .... I can't find p30103 in RDA and how can I learn more about item - minted, I don't know what minted mean. And (manifestation the MARC is describing), does it mean MARC describe the item at manifestation level?

**Comment by GordonDunsire** [comment]
> I find the element " item described with metadata by" is a subtype of "item described by". What does the "metadata" mean here specifically?

The definition of rdai:P40164 'item described with metadata by' is 'A work that is a metadata work for an item'. A metadata work is 'a metadata statement or a metadata description set'. A metadata statement is 'a piece of metadata that assigns a value to an RDA element that describes an individual instance of an RDA entity', and a metadata description set is an aggregation of such statements. So the essential feature of metadata is that it is structured, and typical examples range from a single statement such as 'this item has owner agent 'My Library Service'', to a set of statements about the item, to a catalogue that consists of sets of statements about multiple manifestations that are exemplified by items in a collection.

The element super-type rdai:P40062 'item described by' has a broader definition, 'a description of an item' that also covers unstructured 'metadata'; that is, an uncontrolled narrative or discursive work about a particular item. Examples include a history of a specific rare or special book, a description of the curation of a museum object, a television programme about the provenance of a painting (such as the BBC's 'Fake or fortune?' series), etc.

Sibling elements are rdai:P4003 'item analysed in' and rdai:P40064 'item commentary in' which cover specific kinds of unstructured descriptive data. These are legacy elements, while rdai:P40164 'item described with metadata by' is a new element that is consistent with collection-description including catalogues, and other kinds of finding-aid.

**Comment by CECSpecialistI** [comment]
Reviewed during meeting today.
