### ISSUE TITLE
555 cumulative index/finding aid note

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#223]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by dchen077** [comment]
@pennylenger Hi Penny, just to clarify if the transform note for $3 is suppose to be "applies to" and not "material specified"? If so, I'll go ahead and correct that in the code. Thanks!

**Comment by pennylenger** [comment]
Yes, it is "applies to".
