### ISSUE TITLE
562 copy and version identification note

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#226]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by CECSpecialistI** [comment]
Hi! @cspayne and I are looking at this MARC field and can't figure out which RDA entity each subfield relates to. On first glance, it looks like each subfield corresponds to either an RDA item or RDA manifestation. But without examples in the MARC format, we aren't 100% sure. 

It looks like the "item-level" subfields can include information about multiple items, and it's unclear whether those descriptions which apply to more than one item will also consistently include a $e detailing the number of items. The description for $c "Version identification" makes it difficult to tell whether "version" describes a manifestation or expression: "Information such as names, codes, or descriptions used to identify a version that differs in content but is related across time to another version, such as an edition." Are these always local notes with $5? 
@AdamSchiff @GordonDunsire @szapoun @lake44me

**Comment by GordonDunsire** [comment]
I wouldn't transform this tag because the semantics are too diffuse. I agree that the data pertains to Manifestation or Item. The context seems to be "miscellaneous hand-made resources" (because states and versions are excluded). I think this implies no pattern in the distinction between Manifestation and Item because they were treated as interchangeable in pre-FRBR cataloguing.

**Comment by CECSpecialistI** [comment]
@GordonDunsire how would you feel about these being mapped as notes on item when there is a $5 associated with the field, and not mapped when there is no $5? Is that safe, or would you favor not mapping the entire field regardless of the presence of a $5?

**Comment by GordonDunsire** [comment]
@CECSpecialistI: I don't think subfield $5 is relevant: we still don't know if the data pertains to one (unidentified) item or multiple items or a collection (of items) ... and then there is the general problem of the "local" nature of subfield $5 and its current validity.

**Comment by CECSpecialistI** [comment]
Going with @GordonDunsire 's suggestion not to map due to diffuse semantics.
