### ISSUE TITLE
647 subject added entry--named event

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#243]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/6XX.csv

**Comment by cspayne** [comment]
@CECSpecialistI @GordonDunsire
I was assigned field 647 and 648 for mapping, but I believe they may fall under Gordon's document. Should I leave these to you Gordon?

**Comment by CECSpecialistI** [comment]
Yeah @cspayne I think you should hold off on these until Gordon's document is complete. It's likely that he's going to hand it off to you and Penny soon.

**Comment by cspayne** [comment]
Hi @pennylenger 
I think $x, $y, and $z mappings still need to be added to this google sheet. Are they treated the same as in field 650?

**Comment by cspayne** [comment]
Also, why are $0 and $1 not used as the value for "has subject" in this field?

**Comment by pennylenger** [comment]
Hi Cypress, I asked a question about this:
If $0 references the complete heading as an event which is not an RDA entity, why can’t we use the converted URI as the object of the triple? If there is a $1, can we use it? And should we mint a skos:concept for the complete heading for 647?
Example 66
647 7 $a World War $d (1939-1945) $2 fast $0 (OCoLC)fst01180924
rdawo:P10322 . // has subject timespan; ignore subfield $0 which references the complete heading as an event (not an RDA entity)
rdato:P70047 . // has authorized access point for timespan
rdand:P80068 “1939-1945” . // has nomen string
rdano:P80069 http://id.loc.gov/vocabulary/subjectSchemes/fast . // has scheme of nomen

Adam: I don't think you can say that there is a FAST authorized access point for timespan that is derived from the $d of a 647 field.  The authorized access point in 647 is for an event, not a timespan.
To say that there is an authorized access point from FAST with nomen string 1939-1945 there must be a FAST authority for that timespan by itself, not as part of an access point for an event.

Gordon: OK, I have changed example 66, 647 output to be just a subject heading from FAST; that is, as a skos:Concept. This is the approach we can take if we decide not to normalize the subfield $0 URI and mint our own. Note that example 66 also includes the corresponding 648 field.

**Comment by pennylenger** [comment]
> Hi @pennylenger I think $x, $y, and $z mappings still need to be added to this google sheet. Are they treated the same as in field 650?

I will add this. Thank you.

**Comment by cspayne** [comment]
> Hi Cypress, I asked a question about this: If $0 references the complete heading as an event which is not an RDA entity, why can’t we use the converted URI as the object of the triple? If there is a $1, can we use it? And should we mint a skos:concept for the complete heading for 647? Example 66 647 7 $a World War $d (1939-1945) $2 fast $0 (OCoLC)fst01180924 rdawo:P10322 . // has subject timespan; ignore subfield $0 which references the complete heading as an event (not an RDA entity) rdato:P70047 . // has authorized access point for timespan rdand:P80068 “1939-1945” . // has nomen string rdano:P80069 http://id.loc.gov/vocabulary/subjectSchemes/fast . // has scheme of nomen
> 
> Adam: I don't think you can say that there is a FAST authorized access point for timespan that is derived from the $d of a 647 field. The authorized access point in 647 is for an event, not a timespan. To say that there is an authorized access point from FAST with nomen string 1939-1945 there must be a FAST authority for that timespan by itself, not as part of an access point for an event.
> 
> Gordon: OK, I have changed example 66, 647 output to be just a subject heading from FAST; that is, as a skos:Concept. This is the approach we can take if we decide not to normalize the subfield $0 URI and mint our own. Note that example 66 also includes the corresponding 648 field.

Hi Penny, thank you for this. I think what this means is that we can't use FAST URIs for subfield $d in 647 as a timespan. However, since the field as a whole is being mapped to a skos:concept, I believe we can use $0 or $1 for that value, as [work] has subject [value of $0 or $1] like in field 650.

**Comment by pennylenger** [comment]
> > Hi Cypress, I asked a question about this: If $0 references the complete heading as an event which is not an RDA entity, why can’t we use the converted URI as the object of the triple? If there is a $1, can we use it? And should we mint a skos:concept for the complete heading for 647? Example 66 647 7 $a World War $d (1939-1945) $2 fast $0 (OCoLC)fst01180924 rdawo:P10322 . // has subject timespan; ignore subfield $0 which references the complete heading as an event (not an RDA entity) rdato:P70047 . // has authorized access point for timespan rdand:P80068 “1939-1945” . // has nomen string rdano:P80069 http://id.loc.gov/vocabulary/subjectSchemes/fast . // has scheme of nomen
> > Adam: I don't think you can say that there is a FAST authorized access point for timespan that is derived from the $d of a 647 field. The authorized access point in 647 is for an event, not a timespan. To say that there is an authorized access point from FAST with nomen string 1939-1945 there must be a FAST authority for that timespan by itself, not as part of an access point for an event.
> > Gordon: OK, I have changed example 66, 647 output to be just a subject heading from FAST; that is, as a skos:Concept. This is the approach we can take if we decide not to normalize the subfield $0 URI and mint our own. Note that example 66 also includes the corresponding 648 field.
> 
> Hi Penny, thank you for this. I think what this means is that we can't use FAST URIs for subfield $d in 647 as a timespan. However, since the field as a whole is being mapped to a skos:concept, I believe we can use $0 or $1 for that value, as [work] has subject [value of $0 or $1] like in field 650.

Okay, I'll wait a bit to see if there are any other changes needed in 6XX, then I'll make all the modifications together in Google Sheet. I hope this won't affect your coding.

**Comment by cspayne** [comment]
Sounds good! No, there's no hold up, I can adjust the code as needed!

**Comment by szapoun** [comment]
@cspayne added lines for $x$y$z and fast. Please review
