### ISSUE TITLE
650 subject added entry--topical term

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#245]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/6XX.csv

**Comment by GordonDunsire** [comment]
This overlaps with the discussion on [Classification numbers](https://github.com/uwlib-cams/MARC2RDA/discussions/434). We should use a consistent approach and expand the scope of the Google doc to cover the <work> <has subject> aspects of 6XX.

**Comment by szapoun** [comment]
@cspayne I have added 3 lines for breaking out fast $x$y$z. I did not put status: reviewed, but first pass. Can you please check if they are ok according to the new decision? If yes, I will implement to the other tags too. Thank you

**Comment by cspayne** [comment]
Hi @szapoun. They look good!

**Comment by cspayne** [comment]
Hi @szapoun, it was clarified in the meeting today that we will not be breaking out any $x, $y, or $z from subjects, we will mint subject concepts as a whole. fast will sometimes break out $x, $y, or $z from other subject headings and create separate fields for those values, which we will retain, such as the below example. These do not require any additions to the mappings we have already created.
```
      <marc:datafield tag="655" ind1=" " ind2="7">
            <marc:subfield code="a">History.</marc:subfield>
            <marc:subfield code="2">fast</marc:subfield>
            <marc:subfield code="0">(OCoLC)fst01411628</marc:subfield>
     </marc:datafield>
```

@GordonDunsire @CECSpecialistI can you confirm that this is correct? Thanks.

**Comment by cspayne** [comment]
Are we separating out $v as a category of work even if an IRI is provided for the entire subject in $1 or $0? Or do we only separate out $v if we are also minting an IRI for the subject as a whole?

**Comment by pennylenger** [comment]
I am not sure but I think we should separate out $v.  We can check with  @GordonDunsire @AdamSchiff:

- Are we separating out $v as a category of work even if an IRI is provided for the entire subject in $1 or $0? 
- Or do we only separate out $v if we are also minting an IRI for the subject as a whole?

**Comment by AdamSchiff** [comment]
I believe that we are keeping the entire string as the subject, including the $v and that we are also separating out the $v as category of work.

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________
