### ISSUE TITLE
651 subject added entry--geographic name

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#246]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/6XX.csv

**Comment by cspayne** [comment]
The mapping shows that we are adding an authorized access point to IRIs provided in $0's and $1's for places with the authorized access point being the combined values of $a and $g. I have two questions related to this:

1. Why are we not minting a nomen for the authorized access point here, while we are for the authorized access point when we mint our own IRI?
2. Why is the authorized access point $a and $g here but only $a when we mint our own IRI?

I suggest that we decide whether to use $a and $g or only $a and be consistent, as well as decide how these values should be combined (separated by a space or by --). We should also be consistent in minting a nomen for an authorized access point when we have a source and using a string value as an access point (not authorized) with no source. 

If we are in agreement about this, I can update the mapping and the code.

**Comment by cspayne** [comment]
Here's one example from gnd for Mexico City:

```
<marc:datafield tag="651" ind1=" " ind2="7">
            <marc:subfield code="a">Mexiko</marc:subfield>
            <marc:subfield code="g">Stadt</marc:subfield>
            <marc:subfield code="2">gnd</marc:subfield>
</marc:datafield>
```

**Comment by GordonDunsire** [comment]
@cspayne: The example of subfield $g is bad data, and unfortunately it may be a hint of a larger problem. The value 'stadt' is German for 'city', so the intended place is 'Mexico City' or 'Mexico (city)'. In both cases these should be recorded as subfield $a: the MARC 21 manual explicitly states for subfield $a 'Parenthetical qualifying information is not separately subfield coded'. I am wondering if this is an import artefact rather than a simple cataloguer error, arising from the inclusion of DNB authority data in M21. But we don't need to know how it has happened because the result for the transform is the same: only use $a for the AAP, as the manual instructs.

In the case of this example, this will output Mexico the country instead of Mexico City, but it is not invalid because Mexico City the place is part of Mexico the place :-)

If we can determine that if source is 'gnd' then subfield $g is a placename qualifier, then the values can be concatenated, but I think we have run out of time to make this a safe decision. There is an alternative: concatenate subfields $a and $g, but output the value as an AP, not an AAP.

**Comment by cspayne** [comment]
I haven't found any with subfield $g that aren't from gnd, but I found a few more examples from gnd: 
```xml
        <marc:datafield tag="651" ind1=" " ind2="7">
            <marc:subfield code="a">Südafrika</marc:subfield>
            <marc:subfield code="g">Kontinent</marc:subfield>
            <marc:subfield code="2">gnd</marc:subfield>
        </marc:datafield>
        <marc:datafield tag="651" ind1=" " ind2="7">
            <marc:subfield code="a">Griechenland</marc:subfield>
            <marc:subfield code="g">Altertum</marc:subfield>
            <marc:subfield code="2">gnd</marc:subfield>
        </marc:datafield>
        <marc:datafield tag="651" ind1=" " ind2="7">
            <marc:subfield code="a">East End</marc:subfield>
            <marc:subfield code="g">London</marc:subfield>
            <marc:subfield code="2">gnd</marc:subfield>
        </marc:datafield>
```
@AdamSchiff do you know if $g is commonly used as part of the access point for gnd? 
If Adam doesn't know then I agree with Gordon, we should just use $a at this point.

**Comment by AdamSchiff** [comment]
If you look at a GND authority, the $g is being used as the qualifier to a heading, and I think it's an integral part of the authorized access point.  You should not ignore it, as without the qualifier, the meaning is often ambiguous.

For example, for East End of London, here's the GND authority: https://d-nb.info/gnd/4138902-5

[cid:a79b446c-47eb-43ce-b087-0d8d9f2fcdf6]
You can see that the authorized access point is East End (London), and the variant access point is London- East End.  If you look at it in MARC21 you can see the encoding does use $g for the qualifier (London):

<?xml version="1.0" encoding="UTF-8"?>
  <record xmlns="http://www.loc.gov/MARC21/slim" type="Authority">
    <leader>00000nz  a2200000nc 4500</leader>
    <controlfield tag="001">041389026</controlfield>
    <controlfield tag="003">DE-101</controlfield>
    <controlfield tag="005">20200527132957.0</controlfield>
    <controlfield tag="008">880701n||azznnaabn           | ana    |c</controlfield>
    <datafield tag="024" ind1="7" ind2=" ">
      <subfield code="a">4138902-5</subfield>
      <subfield code="0">http://d-nb.info/gnd/4138902-5</subfield>
      <subfield code="2">gnd</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(DE-101)041389026</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(DE-588)4138902-5</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="z">(DE-588c)4138902-5</subfield>
      <subfield code="9">v:zg</subfield>
    </datafield>
    <datafield tag="040" ind1=" " ind2=" ">
      <subfield code="a">DE-101</subfield>
      <subfield code="c">DE-101</subfield>
      <subfield code="9">r:DE-101</subfield>
      <subfield code="b">ger</subfield>
      <subfield code="d">1150</subfield>
    </datafield>
    <datafield tag="042" ind1=" " ind2=" ">
      <subfield code="a">gnd1</subfield>
    </datafield>
    <datafield tag="043" ind1=" " ind2=" ">
      <subfield code="c">XA-GB</subfield>
    </datafield>
    <datafield tag="075" ind1=" " ind2=" ">
      <subfield code="b">g</subfield>
      <subfield code="2">gndgen</subfield>
    </datafield>
    <datafield tag="075" ind1=" " ind2=" ">
      <subfield code="b">gik</subfield>
      <subfield code="2">gndspec</subfield>
    </datafield>
    <datafield tag="079" ind1=" " ind2=" ">
      <subfield code="a">g</subfield>
      <subfield code="q">s</subfield>
      <subfield code="u">w</subfield>
    </datafield>
    <datafield tag="083" ind1="0" ind2="4">
      <subfield code="z">2</subfield>
      <subfield code="a">4215</subfield>
      <subfield code="9">d:2</subfield>
      <subfield code="9">t:2020-05-27</subfield>
      <subfield code="2">23/ger</subfield>
    </datafield>
    <datafield tag="151" ind1=" " ind2=" ">
      <subfield code="a">East End</subfield>
      <subfield code="g">London</subfield>
    </datafield>
    <datafield tag="451" ind1=" " ind2=" ">
      <subfield code="a">London- East End</subfield>
    </datafield>
    <datafield tag="551" ind1=" " ind2=" ">
      <subfield code="0">(DE-101)040743357</subfield>
      <subfield code="0">(DE-588)4074335-4</subfield>
      <subfield code="0">https://d-nb.info/gnd/4074335-4</subfield>
      <subfield code="a">London</subfield>
      <subfield code="4">adue</subfield>
      <subfield code="4">https://d-nb.info/standards/elementset/gnd#hierarchicalSuperiorOfPlaceOrGeographicName</subfield>
      <subfield code="w">r</subfield>
      <subfield code="i">Ueberordnung</subfield>
    </datafield>
    <datafield tag="670" ind1=" " ind2=" ">
      <subfield code="a">M unter London</subfield>
    </datafield>
    <datafield tag="913" ind1=" " ind2=" ">
      <subfield code="S">swd</subfield>
      <subfield code="i">g</subfield>
      <subfield code="a">London- East End</subfield>
      <subfield code="0">(DE-588c)4138902-5</subfield>
    </datafield>
  </record>

I looked for other GND authorities by searching in Wikidata, and it appears that $g is used regularly for qualifiers for city sections.  For example for the Schöneberg neighborhood in Berlin (https://d-nb.info/gnd/4106612-1):

<?xml version="1.0" encoding="UTF-8"?>
  <record xmlns="http://www.loc.gov/MARC21/slim" type="Authority">
    <leader>00000nz  a2200000nc 4500</leader>
    <controlfield tag="001">04106612X</controlfield>
    <controlfield tag="003">DE-101</controlfield>
    <controlfield tag="005">20221011120125.0</controlfield>
    <controlfield tag="008">880701n||azznnaabn           | ana    |c</controlfield>
    <datafield tag="024" ind1="7" ind2=" ">
      <subfield code="a">4106612-1</subfield>
      <subfield code="0">http://d-nb.info/gnd/4106612-1</subfield>
      <subfield code="2">gnd</subfield>
    </datafield>
    <datafield tag="024" ind1="7" ind2=" ">
      <subfield code="a">7290254</subfield>
      <subfield code="2">geonames</subfield>
    </datafield>
    <datafield tag="034" ind1=" " ind2=" ">
      <subfield code="d">E 013 20 51</subfield>
      <subfield code="e">E 013 20 51</subfield>
      <subfield code="f">N 052 29 01</subfield>
      <subfield code="g">N 052 29 01</subfield>
      <subfield code="2">geonames</subfield>
      <subfield code="0">https://sws.geonames.org/7290254</subfield>
      <subfield code="9">A:agx</subfield>
    </datafield>
    <datafield tag="034" ind1=" " ind2=" ">
      <subfield code="d">E013.347699</subfield>
      <subfield code="e">E013.347699</subfield>
      <subfield code="f">N052.483879</subfield>
      <subfield code="g">N052.483879</subfield>
      <subfield code="2">geonames</subfield>
      <subfield code="0">https://sws.geonames.org/7290254</subfield>
      <subfield code="9">A:dgx</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(DE-101)04106612X</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(DE-588)4106612-1</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="z">(DE-588)17567-5</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="z">(DE-588b)17567-5</subfield>
      <subfield code="9">v:zg</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="z">(DE-588c)4106612-1</subfield>
      <subfield code="9">v:zg</subfield>
    </datafield>
    <datafield tag="040" ind1=" " ind2=" ">
      <subfield code="a">DE-101</subfield>
      <subfield code="c">DE-101</subfield>
      <subfield code="9">r:DE-101</subfield>
      <subfield code="b">ger</subfield>
      <subfield code="d">0025</subfield>
    </datafield>
    <datafield tag="042" ind1=" " ind2=" ">
      <subfield code="a">gnd1</subfield>
    </datafield>
    <datafield tag="043" ind1=" " ind2=" ">
      <subfield code="c">XA-DXDE</subfield>
      <subfield code="c">XA-DE-BE</subfield>
    </datafield>
    <datafield tag="075" ind1=" " ind2=" ">
      <subfield code="b">g</subfield>
      <subfield code="2">gndgen</subfield>
    </datafield>
    <datafield tag="075" ind1=" " ind2=" ">
      <subfield code="b">gik</subfield>
      <subfield code="2">gndspec</subfield>
    </datafield>
    <datafield tag="079" ind1=" " ind2=" ">
      <subfield code="a">g</subfield>
      <subfield code="q">s</subfield>
      <subfield code="q">f</subfield>
      <subfield code="u">w</subfield>
      <subfield code="u">z</subfield>
      <subfield code="u">v</subfield>
      <subfield code="u">o</subfield>
    </datafield>
    <datafield tag="083" ind1="0" ind2="4">
      <subfield code="z">2</subfield>
      <subfield code="a">43155</subfield>
      <subfield code="9">t:2009-09-17</subfield>
      <subfield code="2">23/ger</subfield>
    </datafield>
    <datafield tag="151" ind1=" " ind2=" ">
      <subfield code="a">Schöneberg</subfield>
      <subfield code="g">Berlin</subfield>
    </datafield>
    <datafield tag="410" ind1="2" ind2=" ">
      <subfield code="a">Schöneberg</subfield>
      <subfield code="g">Berlin</subfield>
      <subfield code="b">Magistrat</subfield>
      <subfield code="4">spio</subfield>
      <subfield code="4">https://d-nb.info/standards/elementset/gnd#variantName</subfield>
      <subfield code="w">r</subfield>
      <subfield code="i">Spitzenorgan</subfield>
      <subfield code="e">Spitzenorgan</subfield>
    </datafield>
    <datafield tag="410" ind1="2" ind2=" ">
      <subfield code="a">Magistrat</subfield>
      <subfield code="g">Schöneberg, Berlin</subfield>
      <subfield code="4">spio</subfield>
      <subfield code="4">https://d-nb.info/standards/elementset/gnd#variantName</subfield>
      <subfield code="w">r</subfield>
      <subfield code="i">Spitzenorgan</subfield>
      <subfield code="e">Spitzenorgan</subfield>
    </datafield>
    <datafield tag="451" ind1=" " ind2=" ">
      <subfield code="a">Berlin</subfield>
      <subfield code="g">Kreis Teltow</subfield>
    </datafield>
    <datafield tag="451" ind1=" " ind2=" ">
      <subfield code="a">Stadt Schöneberg</subfield>
      <subfield code="9">v:1898-1911</subfield>
    </datafield>
    <datafield tag="451" ind1=" " ind2=" ">
      <subfield code="a">Berlin-Schöneberg</subfield>
      <subfield code="g">1912-1920</subfield>
    </datafield>
    <datafield tag="548" ind1=" " ind2=" ">
      <subfield code="a">1874-1920</subfield>
      <subfield code="4">datb</subfield>
      <subfield code="4">https://d-nb.info/standards/elementset/gnd#dateOfEstablishmentAndTermination</subfield>
      <subfield code="w">r</subfield>
      <subfield code="i">Zeitraum</subfield>
    </datafield>
    <datafield tag="551" ind1=" " ind2=" ">
      <subfield code="0">(DE-101)001169440</subfield>
      <subfield code="0">(DE-588)116944-0</subfield>
      <subfield code="0">https://d-nb.info/gnd/116944-0</subfield>
      <subfield code="a">Alt-Schöneberg</subfield>
      <subfield code="4">vorg</subfield>
      <subfield code="4">https://d-nb.info/standards/elementset/gnd#precedingPlaceOrGeographicName</subfield>
      <subfield code="w">r</subfield>
      <subfield code="i">Vorgaenger</subfield>
    </datafield>
    <datafield tag="551" ind1=" " ind2=" ">
      <subfield code="0">(DE-101)040873404</subfield>
      <subfield code="0">(DE-588)4087340-7</subfield>
      <subfield code="0">https://d-nb.info/gnd/4087340-7</subfield>
      <subfield code="a">Berlin-Schöneberg</subfield>
      <subfield code="4">nach</subfield>
      <subfield code="4">https://d-nb.info/standards/elementset/gnd#succeedingPlaceOrGeographicName</subfield>
      <subfield code="w">r</subfield>
      <subfield code="i">Nachfolger</subfield>
    </datafield>
    <datafield tag="551" ind1=" " ind2=" ">
      <subfield code="0">(DE-101)040057283</subfield>
      <subfield code="0">(DE-588)4005728-8</subfield>
      <subfield code="0">https://d-nb.info/gnd/4005728-8</subfield>
      <subfield code="a">Berlin</subfield>
      <subfield code="4">obpa</subfield>
      <subfield code="4">https://d-nb.info/standards/elementset/gnd#broaderTermPartitive</subfield>
      <subfield code="w">r</subfield>
      <subfield code="i">Oberbegriff partitiv</subfield>
      <subfield code="9">X:1</subfield>
    </datafield>
    <datafield tag="667" ind1=" " ind2=" ">
      <subfield code="a">MMi</subfield>
    </datafield>
    <datafield tag="670" ind1=" " ind2=" ">
      <subfield code="a">M</subfield>
    </datafield>
    <datafield tag="670" ind1=" " ind2=" ">
      <subfield code="b">Stand: 20.01.2022</subfield>
      <subfield code="u">https://de.wikipedia.org/wiki/Berlin-Sch%C3%B6neberg</subfield>
    </datafield>
    <datafield tag="678" ind1=" " ind2=" ">
      <subfield code="b">Stadt südlich von Berlin am Nordrand des Teltow, wahrscheinlich 1. Drittel 13. Jh. als Straßendorf gegründet, 1874 Zusammenschluss von Alt- und Neu-Schöneberg (um 1750 gegründet), 1.4.1898 Stadtrecht im Landkreis Teltow, 1.4.1899 kreisfrei, 1.4.1912 zum Zweckverband Groß-Berlin, seitdem Berlin-Schöneberg, 1.10.1920 als 11. Bezirk nach Berlin eingemeindet</subfield>
    </datafield>
    <datafield tag="913" ind1=" " ind2=" ">
      <subfield code="S">swd</subfield>
      <subfield code="i">g</subfield>
      <subfield code="a">Schöneberg &lt;Berlin&gt;</subfield>
      <subfield code="0">(DE-588c)4106612-1</subfield>
    </datafield>
    <datafield tag="913" ind1=" " ind2=" ">
      <subfield code="S">gkd</subfield>
      <subfield code="i">a</subfield>
      <subfield code="a">Schöneberg &lt;Berlin&gt;</subfield>
      <subfield code="0">(DE-588b)17567-5</subfield>
    </datafield>
  </record>

The qualifier in $g is also used for celestial bodies (https://d-nb.info/gnd/4179170-8):

<?xml version="1.0" encoding="UTF-8"?>
  <record xmlns="http://www.loc.gov/MARC21/slim" type="Authority">
    <leader>00000nz  a2200000nc 4500</leader>
    <controlfield tag="001">041791703</controlfield>
    <controlfield tag="003">DE-101</controlfield>
    <controlfield tag="005">20240308153540.0</controlfield>
    <controlfield tag="008">880701n||azznnbabn           | ana    |c</controlfield>
    <datafield tag="024" ind1="7" ind2=" ">
      <subfield code="a">4179170-8</subfield>
      <subfield code="0">http://d-nb.info/gnd/4179170-8</subfield>
      <subfield code="2">gnd</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(DE-101)041791703</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(DE-588)4179170-8</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="z">(DE-588c)4179170-8</subfield>
      <subfield code="9">v:zg</subfield>
    </datafield>
    <datafield tag="040" ind1=" " ind2=" ">
      <subfield code="a">DE-101</subfield>
      <subfield code="c">DE-101</subfield>
      <subfield code="9">r:DE-101</subfield>
      <subfield code="b">ger</subfield>
      <subfield code="d">9999</subfield>
    </datafield>
    <datafield tag="042" ind1=" " ind2=" ">
      <subfield code="a">gnd1</subfield>
    </datafield>
    <datafield tag="043" ind1=" " ind2=" ">
      <subfield code="c">XN</subfield>
    </datafield>
    <datafield tag="065" ind1=" " ind2=" ">
      <subfield code="a">20</subfield>
      <subfield code="2">sswd</subfield>
    </datafield>
    <datafield tag="075" ind1=" " ind2=" ">
      <subfield code="b">g</subfield>
      <subfield code="2">gndgen</subfield>
    </datafield>
    <datafield tag="075" ind1=" " ind2=" ">
      <subfield code="b">gix</subfield>
      <subfield code="2">gndspec</subfield>
    </datafield>
    <datafield tag="079" ind1=" " ind2=" ">
      <subfield code="a">g</subfield>
      <subfield code="q">s</subfield>
      <subfield code="u">w</subfield>
    </datafield>
    <datafield tag="083" ind1="0" ind2="4">
      <subfield code="z">2</subfield>
      <subfield code="a">9926</subfield>
      <subfield code="9">d:3</subfield>
      <subfield code="9">t:2007-01-01</subfield>
      <subfield code="2">23/ger</subfield>
    </datafield>
    <datafield tag="083" ind1="0" ind2="4">
      <subfield code="a">523.46</subfield>
      <subfield code="9">d:3</subfield>
      <subfield code="9">t:2007-01-01</subfield>
      <subfield code="2">23/ger</subfield>
    </datafield>
    <datafield tag="083" ind1="0" ind2="4">
      <subfield code="a">133.537</subfield>
      <subfield code="9">d:3</subfield>
      <subfield code="9">t:2015-07-03</subfield>
      <subfield code="2">23/ger</subfield>
    </datafield>
    <datafield tag="151" ind1=" " ind2=" ">
      <subfield code="a">Saturn</subfield>
      <subfield code="g">Planet</subfield>
    </datafield>
    <datafield tag="550" ind1=" " ind2=" ">
      <subfield code="0">(DE-101)040462129</subfield>
      <subfield code="0">(DE-588)4046212-2</subfield>
      <subfield code="0">https://d-nb.info/gnd/4046212-2</subfield>
      <subfield code="a">Planet</subfield>
      <subfield code="4">obin</subfield>
      <subfield code="4">https://d-nb.info/standards/elementset/gnd#broaderTermInstantial</subfield>
      <subfield code="w">r</subfield>
      <subfield code="i">Oberbegriff instantiell</subfield>
      <subfield code="9">X:1</subfield>
    </datafield>
    <datafield tag="670" ind1=" " ind2=" ">
      <subfield code="a">SWL</subfield>
    </datafield>
    <datafield tag="751" ind1=" " ind2="7">
      <subfield code="0">(DE-101)1134041160</subfield>
      <subfield code="0">(DLC)sh85117690</subfield>
      <subfield code="0">http://id.loc.gov/authorities/subjects/sh85117690</subfield>
      <subfield code="a">Saturn (Planet)</subfield>
      <subfield code="4">EQ</subfield>
      <subfield code="4">https://d-nb.info/standards/elementset/gnd#equivalence</subfield>
      <subfield code="i">Aequivalenz</subfield>
      <subfield code="2">lcsh</subfield>
      <subfield code="9">L:eng</subfield>
    </datafield>
    <datafield tag="751" ind1=" " ind2="7">
      <subfield code="0">(DE-101)1134041160</subfield>
      <subfield code="0">(FrPBN)FRBNF11976363</subfield>
      <subfield code="0">https://data.bnf.fr/ark:/12148/cb11976363g</subfield>
      <subfield code="a">Saturne (planète)</subfield>
      <subfield code="4">EQ</subfield>
      <subfield code="4">https://d-nb.info/standards/elementset/gnd#equivalence</subfield>
      <subfield code="i">Aequivalenz</subfield>
      <subfield code="2">ram</subfield>
      <subfield code="9">L:fre</subfield>
    </datafield>
    <datafield tag="913" ind1=" " ind2=" ">
      <subfield code="S">swd</subfield>
      <subfield code="i">s</subfield>
      <subfield code="a">Saturn &lt;Planet&gt;</subfield>
      <subfield code="0">(DE-588c)4179170-8</subfield>
    </datafield>
  </record>

Here's the GND record for Mississippi River, which in GND is established as Mississippi (Fluss) (https://d-nb.info/gnd/4039589-3<https://d-nb.info/gnd/4039589-3>😄

<?xml version="1.0" encoding="UTF-8"?>
  <record xmlns="http://www.loc.gov/MARC21/slim" type="Authority">
    <leader>00000nz  a2200000nc 4500</leader>
    <controlfield tag="001">040395898</controlfield>
    <controlfield tag="003">DE-101</controlfield>
    <controlfield tag="005">20230818063143.0</controlfield>
    <controlfield tag="008">880701n||azznnbabn           | ana    |c</controlfield>
    <datafield tag="024" ind1="7" ind2=" ">
      <subfield code="a">4039589-3</subfield>
      <subfield code="0">http://d-nb.info/gnd/4039589-3</subfield>
      <subfield code="2">gnd</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(DE-101)040395898</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">(DE-588)4039589-3</subfield>
    </datafield>
    <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="z">(DE-588c)4039589-3</subfield>
      <subfield code="9">v:zg</subfield>
    </datafield>
    <datafield tag="040" ind1=" " ind2=" ">
      <subfield code="a">DE-101</subfield>
      <subfield code="c">DE-101</subfield>
      <subfield code="9">r:DE-101</subfield>
      <subfield code="b">ger</subfield>
      <subfield code="d">9999</subfield>
    </datafield>
    <datafield tag="042" ind1=" " ind2=" ">
      <subfield code="a">gnd1</subfield>
    </datafield>
    <datafield tag="043" ind1=" " ind2=" ">
      <subfield code="c">XD-US</subfield>
    </datafield>
    <datafield tag="065" ind1=" " ind2=" ">
      <subfield code="a">19.3</subfield>
      <subfield code="2">sswd</subfield>
    </datafield>
    <datafield tag="075" ind1=" " ind2=" ">
      <subfield code="b">g</subfield>
      <subfield code="2">gndgen</subfield>
    </datafield>
    <datafield tag="075" ind1=" " ind2=" ">
      <subfield code="b">gin</subfield>
      <subfield code="2">gndspec</subfield>
    </datafield>
    <datafield tag="079" ind1=" " ind2=" ">
      <subfield code="a">g</subfield>
      <subfield code="q">s</subfield>
      <subfield code="u">w</subfield>
      <subfield code="u">o</subfield>
    </datafield>
    <datafield tag="083" ind1="0" ind2="4">
      <subfield code="z">2</subfield>
      <subfield code="a">77</subfield>
      <subfield code="9">t:2007-01-01</subfield>
      <subfield code="2">23/ger</subfield>
    </datafield>
    <datafield tag="151" ind1=" " ind2=" ">
      <subfield code="a">Mississippi</subfield>
      <subfield code="g">Fluss</subfield>
    </datafield>
    <datafield tag="550" ind1=" " ind2=" ">
      <subfield code="0">(DE-101)041319729</subfield>
      <subfield code="0">(DE-588)4131972-2</subfield>
      <subfield code="0">https://d-nb.info/gnd/4131972-2</subfield>
      <subfield code="a">Fluss</subfield>
      <subfield code="4">obin</subfield>
      <subfield code="4">https://d-nb.info/standards/elementset/gnd#broaderTermInstantial</subfield>
      <subfield code="w">r</subfield>
      <subfield code="i">Oberbegriff instantiell</subfield>
      <subfield code="9">X:1</subfield>
    </datafield>
    <datafield tag="670" ind1=" " ind2=" ">
      <subfield code="a">M</subfield>
    </datafield>
    <datafield tag="751" ind1=" " ind2="7">
      <subfield code="0">(DE-101)992345448</subfield>
      <subfield code="0">(ZBW)091412544</subfield>
      <subfield code="a">Mississippi (Fluss)</subfield>
      <subfield code="4">=EQ</subfield>
      <subfield code="4">https://d-nb.info/standards/elementset/gnd#exactEquivalence</subfield>
      <subfield code="i">exakte Aequivalenz</subfield>
      <subfield code="2">stw</subfield>
    </datafield>
    <datafield tag="913" ind1=" " ind2=" ">
      <subfield code="S">swd</subfield>
      <subfield code="i">g</subfield>
      <subfield code="a">Mississippi &lt;Fluss&gt;</subfield>
      <subfield code="0">(DE-588c)4039589-3</subfield>
    </datafield>
  </record>

In all cases that I've seen, what's in $g is rendered in a label as a qualifier in parentheses:

East End (London)

Schöneberg (Berlin)

Saturn (Planet)

Mississippi (Fluss)

If you drop these qualifiers, the term is no longer clear.  Does "Saturn" refer to a planet, a deity, or an automobile model?  Does "Mississippi" refer to a state or a river?

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***

________________________________

**Comment by GordonDunsire** [comment]
@cspayne, @AdamSchiff: So it looks like a systematic import/matching error: The GND data should have been concatenated and the qualifiers put in parentheses before importing to 651 subfield $a. I assume the transform can rectify this by detecting the source as GND and concatenating subfield $a and subfield $g (with added parentheses to conform to authority norms).

**Comment by cspayne** [comment]
> Don't know. We should be consistent and mint a nomen if there is source so we can preserve the source information.

I also think we should mint a nomen if there is a source. As we discussed yesterday, we cannot determine whether an access point is authorized based on the $1 value. So if there is an approved source with $1 shouldn't we mint a nomen for that authorized access point to retain the source information? If there is no approved source and a $1, that is when we do not mint a nomen.

**Comment by cspayne** [comment]
@GordonDunsire yes! We did :)
