### ISSUE TITLE
654 subject added entry--faceted topical terms

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#249]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/6XX.csv

**Comment by szapoun** [comment]
@cspayne Added one row for mapping of $1 - please review

**Comment by cspayne** [comment]
For 655 we are not mapping $c Facet/hierarchy designation as part of the subject heading, but in this field, 654, we are. Should we not map it here as well?

**Comment by szapoun** [comment]
Yes, do not map either. Thank you Cypress. Στάλθηκε από το iPhone μου28 Οκτ 2024, 1:19 πμ, ο χρήστης «Cypress Payne ***@***.***>» έγραψε:﻿
For 655 we are not mapping $c Facet/hierarchy designation as part of the subject heading, but in this field, 654, we are. Should we not map it here as well?

**Comment by GordonDunsire** [comment]
@cspayne: Subfield c should not be mapped in either 654 or 655 because it is part of the encoding of the subject heading, not of the heading itself.

**Comment by pennylenger** [comment]
I have deleted $c in 654 mapping.

**Comment by CECSpecialistI** [comment]
@cspayne the code for this is no longer on hold, correct?
