### ISSUE TITLE
656 index term--occupation

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#251]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/6XX.csv

**Comment by cwarc** [comment]
https://docs.google.com/spreadsheets/d/1uiwusBka9LE32L5qSJNfgS0rsRGN38qYK2R7p2TrrFk/edit#gid=685676962

Hello Everyone,

Please see the first pass of the spreadsheet for field code 656 - Index Term-Occupation (R). Would someone be able to review it?

Best.

Thanks,
Alice

**Comment by szapoun** [comment]
Did not put any rules regarding fast, because fast is not included in [$2 list](https://www.loc.gov/standards/sourcelist/occupation.html)
