### ISSUE TITLE
657 index term--function

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#252]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/6XX.csv

**Comment by GordonDunsire** [comment]
@szapoun: I also do not think that fields 657 or 658 map to category of work, and they definitely do not map to a subject element.

The best I can think of is to map 658 to rdawd:P10198 'has related work of work', assuming that a curriculum is a work. The subfields should be concatenated into a single string using the display punctuation given in the MARC 21 Bibliographic manual. The source could be concatenated to the end of the string in parentheses.

For 657, there is no obvious RDA entity or element to map to, so I suggest mapping to rdawd:P10330 'has note on work' and preface the string with the boilerplate 'Function: '.

**Comment by szapoun** [comment]
@CECSpecialistI if you agree, I can change the mapping for 657 and 658

**Comment by pennylenger** [comment]
10-23 Meeting decision: note on work

**Comment by cspayne** [comment]
Adjusted note phrasing slightly for consistency with 5XX note.
