### ISSUE TITLE
658 index term--curriculum objective

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#253]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/6XX.csv

**Comment by szapoun** [comment]
I do not know the use of 658 at all. I am not sure if this tag should be mapped to 'category of work'. I have reviewed accepting the mapping and I have only changed one property from object type to datatype.

**Comment by GordonDunsire** [comment]
@szapoun: I agree. I suggest an alternative in my reply to tag 657:

The best I can think of is to map 658 to rdawd:P10198 'has related work of work', assuming that a curriculum is a work. The subfields should be concatenated into a single string using the display punctuation given in the MARC 21 Bibliographic manual. The source could be concatenated to the end of the string in parentheses.

**Comment by pennylenger** [comment]
10-23 Meeting decision: note on work
