### ISSUE TITLE
662 subject added entry--hierarchical place name

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#254]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/6XX.csv

**Comment by cspayne** [comment]
@pennylenger @GordonDunsire 
Should the subfields making up the access point for place in this field be separated by a space or by " -- "?

**Comment by pennylenger** [comment]
I see previous decision is to retain the internal punctuation provided.  If no punctuation is provided, we should insert the same delimiter between components of the heading, for example semi-colon-space or space-hyphen-space. For place, -- maybe better.

**Comment by GordonDunsire** [comment]
@pennylenger: I think we should use space-hyphen-hyphen-space as the delimiter if no punctuation is recorded. This is consistent with other subject fields.

The 'normal' ISBD delimiter is comma-space, but that is when the smallest unit of place (that is, subfield $g or $f) is recorded first, followed by qualifiers for larger and larger places. But the MARC 21 manual examples start with the largest unit of place in subfield $a, followed by smaller and smaller places, so I think comma-space is not appropriate as a delimiter.
