### ISSUE TITLE
Non-existent subfields in spreadsheet: are they in the registry mappings?

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#26]

**Comment by mcm104** [comment]
[results.txt](https://github.com/uwlib-cams/MARC2RDA/files/7530982/results.txt)

So using Python, I cycled through all of the rows in our spreadsheet that had some kind of "Attention: [x] combo does not exist" note on it, then matched those up with the closest equivalent map(s) from the RDA Registry mapping ([as written here](http://www.rdaregistry.info/ttl/Maps/mapRDA2M21B.ttl)). The output is the above linked document `results.txt`.

It's kind of a clunky document, in hindsight I wish I had output it as CSV. If anyone wants, I can take the time to put it into its own spreadsheet, OR I could add the RDA Registry mappings I found into a new column or a notes column in our mapping spreadsheet.

For the .txt file at least, here is the basic structure:
- From UW spreadsheet (a list of the contents of a row from the spreadsheet, excluding our mappings, conditions, and empty columns)
- Notes (the error notes from that row)
- Mapping as it appears in RDA Registry mapping (the closest equivalent RDA Registry mapping(s) verbatim)

If no equivalent mapping was found, it will say "[Mapping not found]" (Ctrl+F to find these, these are rows that are basically our bad and don't actually appear in the RDA Registry mapping). Looks like there are only 8 of these. I can go through and delete these (or label them to be deleted) if desired.

For the others, there are many where the mapping just got interpreted funky in our spreadsheet (e.g. 'MARC 21 Bibliographic 006 /01-03 [identifier] (visual materials)' ended up being read as subfield $-3 which is obviously not what the mapping was trying to say), so these rows would have to be manually replaced with the actual mapping the RDA Registry is trying to articulate. This, I couldn't do without some help interpreting the MARC.

Then, there are some that do appear to be genuine errors in the RDA Registry, e.g. `rdam:P30004 rdakit:hasM21 "MARC 21 Bibliographic 037 ** $0 [identifier]" .`. If desired, I can make up a spreadsheet of these for someone else to send to whoever is in charge of this mapping (looks like the RSC Technical Working Group?).

@CECSpecialistI @AdamSchiff @gerontakos @briesenberg07

**Comment by CECSpecialistI** [comment]
@mcm104 let's add this to the agenda for our next meeting, but your suggestions to delete the spreadsheet rows that were our mistakes and make a spreadsheet of RDA Registry mistakes to report are good ones. Would it be possible to add a specific note like "attn:cleanup" or something similar to the ones that ended up funky in the spreadsheet so someone with more MARC expertise could go through and correct them?

**Comment by mcm104** [comment]
Spreadsheet with RDA Registry mistakes <https://docs.google.com/spreadsheets/d/10R36Yi4-iHelC6N2mDX-293P97U-xm9-gXVjxOkNYWM/edit?usp=sharing>

**Comment by mcm104** [comment]
Spreadsheet with rows for cataloger review: <https://docs.google.com/spreadsheets/d/1-QFsnctaVKdovQiRFuaj1l2OXeUY19ZqWClLPV7Ux4c/edit?usp=sharing> (not a working document; will find these rows in main spreadsheet and add "cleanup" note)

**Comment by mcm104** [comment]
Spreadsheet with rows to delete: <https://docs.google.com/spreadsheets/d/1hGPtcUJBViyMOpZHbFY67JhiiyJX8yzQVi_2qGRBq9I/edit?usp=sharing> (not a working document; will find these rows in main spreadsheet and delete)

**Comment by CECSpecialistI** [comment]
> Spreadsheet with rows for cataloger review: https://docs.google.com/spreadsheets/d/1-QFsnctaVKdovQiRFuaj1l2OXeUY19ZqWClLPV7Ux4c/edit?usp=sharing (not a working document; will find these rows in main spreadsheet and add "cleanup" note)

@CECSpecialistI , @JianPLee and @junghaelee will repair the MARC or indicate which rows are mistakes. Then, @mcm104 will repair working documents accordingly. @CECSpecialistI will email final spreadsheet of mistakes in RDA mapping to RSC after reviewing one more time.

**Comment by CECSpecialistI** [comment]
> > Spreadsheet with rows for cataloger review: https://docs.google.com/spreadsheets/d/1-QFsnctaVKdovQiRFuaj1l2OXeUY19ZqWClLPV7Ux4c/edit?usp=sharing (not a working document; will find these rows in main spreadsheet and add "cleanup" note)
> 
> @CECSpecialistI , @JianPLee and @junghaelee will repair the MARC or indicate which rows are mistakes. Then, @mcm104 will repair working documents accordingly. @CECSpecialistI will email final spreadsheet of mistakes in RDA mapping to RSC after reviewing one more time.

@mcm104  Work by Crystal, Jian and Junghae on the spreadsheet with rows for cataloger review is done, ready for you to repair working documents and add mistakes to "Spreadsheet with RDA Registry Mistakes". Once I get  go-ahead from you, I will send the mistakes spreadsheet on to the RSC technical working group.

**Comment by CECSpecialistI** [comment]
I just sent an email to the RDA/MARC 21 Alignment Task Force within the RSC with Melissa's finalized spreadsheet. Thank you @mcm104 @JianPLee and @junghaelee , hopefully this will make our mapping and the published mapping on the Registry better :)
