### ISSUE TITLE
870 variant personal name [obsolete]

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#306]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/8XX.csv

**Comment by cwarc** [comment]
https://docs.google.com/spreadsheets/d/1e2cGjWGPxPfWQDQ4aQ-KY8unRqJJQP1J0zIxSV_6maI/edit#gid=1792581422

Hello Everyone,

Please see the first pass of Field 870 - Variant Personal Name (BK, AM, MP, MU, VM, SE) [OBSOLETE, 1987]. 

Thank you,
Alice

**Comment by pan-zhuo** [comment]
Note from coder: Could not find sufficient MARC documentation for this field and suggest this field be excluded from mapping.

**Comment by CECSpecialistI** [comment]
I think excluding this from the mapping makes sense.
