### ISSUE TITLE
871 variant corporate name [obsolete]

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#307]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/8XX.csv

**Comment by cwarc** [comment]
https://docs.google.com/spreadsheets/d/1iTPBdK78422zdR_z0RMQv67_1k3WOYe3L9PqnRbyvyQ/edit#gid=454284746

Hello Everyone,

Please see the first pass for field code Field 871 - Variant Corporate Name (BK, AM, MP, MU, VM, SE) [OBSOLETE, 1987]. 

Thank you.

Best,
Alice

**Comment by pan-zhuo** [comment]
Note from coder: Could not find sufficient MARC documentation for this field and suggest this field be excluded from mapping.

**Comment by CECSpecialistI** [comment]
Excluding from the mapping makes sense.
