### ISSUE TITLE
490 series statement

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#320]
mapped collaboratively at beginning of project. may want to review later.

https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/4XX.csv

**Comment by gerontakos** [comment]
When we aligned MARC 490 $a + $x + $v to RDA "has series statement" (P30106), did we overlook a more appropriate property "has manifestation series statement" (P30291)?

**Comment by AdamSchiff** [comment]
I don't think so.  Manifestation series statement would be a direct transcription of what appears on the resource, keeping punctuation, capitalization, etc.  490 is a transcription, but it is still structured.  For example in 490 we'd add a colon to separate a series title and subtitle, or a slash to separate a series statement of responsibility.  We'd add $x with ISSN even if the ISSN appeared on a different source of information.  We normalize some of the numbering as well in 490, whereas in manifestation series statement we'd transcribe spelled-out numerals as is.

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***

________________________________
