### ISSUE TITLE
test mapping 999

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#321]
asdf

**Comment by CECSpecialistI** [comment]
@AdamSchiff what is the MARC 999?

**Comment by AdamSchiff** [comment]
No idea and no such thing in MARC unless locally defined like all of the 9XX fields.

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***

________________________________
