### ISSUE TITLE
look over and improve documentation and instructions for filling out mapping spreadsheet

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#325]

**Comment by mcm104** [comment]
Here is a first pass at converting the spreadsheet to a README: <https://github.com/uwlib-cams/MARC2RDA/blob/main/Instructions/README.md> -- I'm very much welcome to feedback! If we would rather keep it a little more spreadsheet-y, if the new list format is okay, if there are other ideas, etc.

**Comment by mcm104** [comment]
Decided to add a few sample rows from the spreadsheets <https://github.com/uwlib-cams/MARC2RDA/tree/main/Instructions#spreadsheet-structure> -- the rest of the info in the README was copy/pasted from the CSV file, but the info here was written by me, so would definitely welcome any edits or feedback!

@CECSpecialistI
