### ISSUE TITLE
[OBSOLETE] fields, subfields, character positions

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#339]
We decided on 2022-04-13 that we should map obsolete fields/subfields/character positions if they are present in OCLC database. To find out which are used and which are not, Junghae will assemble a list from everything marked [obsolete] in the spreadsheets, and send to OCLC for review. Busy this week, likely sometime next week. Thank you @junghaelee for tackling this one!!

**Comment by CECSpecialistI** [comment]
@junghaelee identified the following problems with the 00x spreadsheet:

- [ ] Instances of the same field/subfield combinations recurring with different labels
- [ ] Erroneous [OBSOLETE] labels throughout (could be a more widespread problem we haven't caught?)
- [ ] Resource types/material types absent for character positions when values depend on them, need to have them populated (MCM had idea of another column...that could work. could also (preferably) use a condition column)
- [ ] Some values have labels but are missing character positions

@mcm104 will follow up on these (thank you!)

@SitaKB is this what you were asking about/related to the problems you were asking about in #50 ?

**Comment by SitaKB** [comment]
@CECSpecialistI Yes, these are the issues I encounter in the 00x spreadsheet.
In the 008 sheet there are also values which are not present in the 008 MARC21 list. I think that those values are from 007.

**Comment by CECSpecialistI** [comment]
Thanks @SitaKB !

**Comment by CECSpecialistI** [comment]
OCLC's Response: 
Hi Junghae,
 
Thank you for contacting OCLC Customer Support. I checked with my colleague regarding your question. We cannot provide a list of obsolete fields/values which still have data in bib records. However you could get this information by running a normal "li:" query using a query collection and then using MARC edit to pull out each field that is obsolete to see what data is entered there:
 
https://help.oclc.org/Metadata_Services/WorldShare_Collection_Manager/Query_collections/Create_a_query_collection_to_get_a_spreadsheet_of_your_holdings/Create_a_spreadsheet_of_your_WorldCat_holdings
 
Please let me know if you have any additional questions,
 
Best,
Lindsay Kelly
OCLC . Customer Support Specialist

**Comment by CECSpecialistI** [comment]
We will need to check on whether obsolete fields/subfields/character positions are being used in source data ourselves. Since they are obsolete, we will not prioritize this work right now, and will put off mapping obsolete fields/subfields/character positions until at least the end of the PCC RDA BSR/CSR milestones.
