### ISSUE TITLE
IGeLU 2022 Presentation Proposal

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#350]
[Call for presentations](https://igelu.org/call-for-presentations/)
Submit proposals via [Proposalspace.com](https://proposalspace.com/calls/d/1411)
Deadline: May 13, 2022.
**Crystal will submit no later than May 12, 2022.**

**Conference Session or Developers' Day?** Conference session <br>
**Lead Presenter:** Crystal Clements <br>
**Co-Presenters:** Crystal, Jian, Laura<br>
**Session title:** Expanding the Foundation for RDA as Linked Data: Mapping MARC21 Bibliographic to LRM/RDA/RDF <br>
**Remote session via IGeLU's account** (Unless someone wants to make the trip to Cardiff? Crystal prefers remote.)<br>
**Abstract:** The University of Washington Libraries is committed to using LRM/RDA/RDF (RDA as linked data) to represent RDA description sets. LRM/RDA/RDF has not been widely adopted, and few test datasets exist. Existing datasets available through Ex Libris products are not complete enough to be useful. This could change rapidly if libraries transform legacy MARC data to LRM/RDA/RDF. Presenters describe a mapping project between the MARC21 bibliographic standard and LRM/RDA/RDF. Such a mapping would be very useful to Ex Libris customers, especially accompanied by an open transformation tool that could be implemented in Alma in the same way the Library of Congress’s MARC-to-BIBFRAME mapping and transform have been. In addition to describing the cross-organizational team, which includes information professionals from the University of Washington, the KB (the National Library of the Netherlands), and Emory University, the presentation addresses project workflows managed at the University of Washington. A live tour of the GitHub repository follows, with demonstrations of the work performed, and a call for additional collaborators. <br>
**Track:** Development/Initiative
* Conference theme: Still here! -- the library's new normal
* Demonstration
* Development/Initiative
* Migration/Implementation
* Practical applications
* Roadmap/update
* Strategy
* User Experience/Discovery
* Meeting (SC, WG, NUG...)
* Other <br>
**Ex Libris Products: Tag the products that your proposal directly relates to. You may tag more than one product. Select 'None--General' for strategy-oriented proposals.**  None-General is best option
*  None - General 
*  360 Services 
* Aleph 
* Alma 
* campusM / Library Mobile 
* Central Discovery Index 
* Esploro 
* Intota 
* Leganto 
* Pivot / Research Professional 
* Primo / Primo VE 
* RapidILL / Rapido 
* Rialto
* Rosetta 
* SFX 
* Summon 
* Voyager 
* Other <br>
**Area of Focus:** Interoperability; Linked Open Data <br>
**Target Audience Skill Level:** Select all options.
**Do you plan to have Ex Libris employees participate in your presentation or meeting?** No.

**Comment by CECSpecialistI** [comment]
@lake44me volunteered for small contribution, such as introduction, if needed. @JianPLee co-presenter

**Comment by gerontakos** [comment]
I'm lurking in the margins waiting to see who will do this. If we don't get enough presenters, I can certainly present.

**Comment by lake44me** [comment]
If Crystal's going to do remote, so should we all.  It would get too tricky otherwise.  They may ask us to record the presentation in advance and just be present for q/a - not sure if they did it that way last year, or if that was some other conference.  It can be helpful if a presenter is from somewhere that has inadequate internet connections to the place where the conference is streaming from.  I wonder how they will handle the combination of remote and on site presentations and remote + on site attendees.  I think the leaders should make an appearance if they can.

**Comment by lake44me** [comment]
I like the description.  I would suggest changing the order in the title to:   RDA as Linked Data, Expanding the Foundation: Mapping MARC21 Bibliographic to LRM/RDA/RDF - that gets the important keywords up front for those looking for them.   I think Development/Initiative is the best category, None/General is best product as Xiaoli suggested, and the other choices sound right.

**Comment by gerontakos** [comment]
I have no improvements to recommend! This looks good.

I'm still available to present but if I'm given the option, I am opting out. But if either Crystal or Jian feel they'd much rather do 6-7 minutes instead of 10, just say so and I'll join the presentation team.

**Comment by JianPLee** [comment]
I have a question regarding to the sentence, "This could change rapidly if libraries transform legacy MARC data to LRM/RDA/RDF." What is "this" referring to? more people will adopt RDA/RDF if more libraries transform legacy MARC data to RDA/RDF?

**Comment by CECSpecialistI** [comment]
i think "this" is referring to the lack of useful test datasets and (as a result), implementations. @gerontakos is that what you meant when you authored this sentence? @JianPLee would it be more clear as "Test datasets robust enough to inform implementation can be produced rapidly if libraries have access to a mapping and conversion tool to transform MARC21 metadata into LRM/RDA/RDF." or something like that?

**Comment by JianPLee** [comment]
Thanks, Crystal. I think it would be more clear with the way you put it or "This could change rapidly if libraries have access to a mapping and conversion tool to transform MARC21 metadata into LRM/RDA/RDF."

**Comment by gerontakos** [comment]
"This" is so often a source of trouble, no? Yes, "this" refers to "that" previous sentence, specifically "few test datasets exist." Jian's change seems good and makes the abstract more relevant to the actual work and deliverables of the project. We could even get rid of the word this:
"However, more LRM/RDA/RDF datasets would appear rapidly if libraries have access to a mapping and conversion tool to transform MARC21 metadata into LRM/RDA/RDF."
????

**Comment by CECSpecialistI** [comment]
Yikes, there's a hard character limit that includes spaces. I ended up needing to make some minor adjustments and submitted this: 
"The University of Washington Libraries is committed to using LRM/RDA/RDF (RDA as linked data) to represent RDA description sets. LRM/RDA/RDF has not been widely adopted, and few test datasets exist. Existing datasets available through Ex Libris products are not complete enough to be useful. However, more LRM/RDA/RDF datasets would appear rapidly if libraries have access to a mapping and conversion tool to transform MARC21 metadata into LRM/RDA/RDF. Presenters describe a mapping project between the MARC21 bibliographic standard and LRM/RDA/RDF. Such a mapping would be very useful to Ex Libris customers, especially accompanied by an open transformation tool that could be implemented in Alma. In addition to describing the cross-organizational team, which includes information professionals from the United States, the Netherlands, Greece, and the United Kingdom, the presentation addresses project workflows managed at the University of Washington. A live tour of the GitHub repository follows, with demonstrations of the work performed, and a call for additional collaborators. "

**Comment by CECSpecialistI** [comment]
@JianPLee @lake44me our proposal was accepted! 

<html>
<body>


Sent: | May 27, 2022 at 5:20 AM
-- | --
From: | François Renaville, University of Liege
Subject: | Proposal Accepted for IGeLU 2022 Hybrid Conference and Developers' Day 12 -15th September, 2022
Call: | IGeLU 2022 Hybrid Conference and Developers' Day 12 -15th September, 2022
Proposal: | MARC-to-RDA Mapping Project Presentation (Expanding the Foundation for RDA as Linked Data: Mapping MARC21 Bibliographic to LRM/RDA/RDF)
Dear Crystal E. Clements,  We are delighted to let you know that your proposal "Expanding the Foundation for RDA as Linked Data: Mapping MARC21 Bibliographic to LRM/RDA/RDF" (ID 1411-85008) has been accepted by the IGeLU 2022 Program Planning Committee and we very much look forward to seeing you in Cardiff or to welcome you online. We will publish later this year some presentation guidelines that hopefully will be helpful to you.  We will be working on the conference program and schedule by the end of June. In order to avoid scheduling conflicts, please make sure you have added as Co-Presenters all colleagues or Ex Libris employees who will participate in your presentation or meeting.  Registration for the IGeLU 2022 Hybrid Conference and Developers' Day will be possible later this spring. We recommend that you finalize travel plans as soon as is practicable.   Closer to the conference date, we will be in contact with more details about the presentation logistics and any other arrangements.   Thank you for your contribution to the IGeLU 2022 Conference! If you have any questions, please address to conference@igelu.org.  Best regards,   François Renaville On behalf of the IGeLU 2022 Program Planning Committee https://igelu.org/event/2022-annual-conference/


</body>
</html>Sent:	May 27, 2022 at 5:20 AM
From:	François Renaville, University of Liege
Subject:	Proposal Accepted for IGeLU 2022 Hybrid Conference and Developers' Day 12 -15th September, 2022
Call:	IGeLU 2022 Hybrid Conference and Developers' Day 12 -15th September, 2022
Proposal:	[MARC-to-RDA Mapping Project Presentation](https://proposalspace.com/proposals/85008) (Expanding the Foundation for RDA as Linked Data: Mapping MARC21 Bibliographic to LRM/RDA/RDF)
Dear Crystal E. Clements,

We are delighted to let you know that your proposal "Expanding the Foundation for RDA as Linked Data: Mapping MARC21 Bibliographic to LRM/RDA/RDF" (ID 1411-85008) has been accepted by the IGeLU 2022 Program Planning Committee and we very much look forward to seeing you in Cardiff or to welcome you online. We will publish later this year some presentation guidelines that hopefully will be helpful to you.

We will be working on the conference program and schedule by the end of June. In order to avoid scheduling conflicts, please make sure you have added as Co-Presenters all colleagues or Ex Libris employees who will participate in your presentation or meeting.

Registration for the IGeLU 2022 Hybrid Conference and Developers' Day will be possible later this spring. We recommend that you finalize travel plans as soon as is practicable. 

Closer to the conference date, we will be in contact with more details about the presentation logistics and any other arrangements. 

Thank you for your contribution to the IGeLU 2022 Conference! If you have any questions, please address to [conference@igelu.org](mailto:conference@igelu.org).

Best regards, 

François Renaville
On behalf of the IGeLU 2022 Program Planning Committee
https://igelu.org/event/2022-annual-conference/

**Comment by CECSpecialistI** [comment]
Crystal, Jian, and Laura will follow up with one another via email once details are provided by the conference committee to plan and deliver the presentation.

**Comment by CECSpecialistI** [comment]
You've got mail
You have a new message in ProposalSpace:
From: [conference@igelu.org](mailto:conference@igelu.org)
Subject: IGeLU 2022 - Program and presentation guidelines
Dear Crystal E. Clements,

You are receiving this email because you are registered as a Presenter or Co-Presenter of a session at the IGeLU 2022 Hybrid Conference and Developers' Day. We are delighted to let you know that the Conference program has now been scheduled:

Session title: Expanding the Foundation for RDA as Linked Data: Mapping MARC21 Bibliographic to LRM/RDA/RDF
Proposal ID: 1411-85008
Date & time: Tuesday, September 13, 2022 at 4:40 PM–5:10 PM (London Time)
Location: 1. Dora Stoutzker Concert Hall	

The full program of the Conference is now available at https://mtgsked.com/p/1411/c . The Developers' Day program will be ready later.

Please note that a location has also been assigned to sessions given remotely since the audience will be composed of physical and virtual participants.

We have prepared some presentation guidelines that hopefully will be helpful to you:
https://drive.google.com/drive/folders/1USZyQQhgkq0yozckq3CGsXcwAE-AqScQ?usp=sharing

We would be happy if you could upload your slides on ProposalSpace before September 6th, 2022. To upload your presentation:
- Go to https://proposalspace.com/ from Monday August 22 and sign in.
- At your dashboard, scroll to the section titled 'Proposals'.
- Locate your session and edit it (your session will be available for edit from August 22).
- Scroll down until section 'Presentation file(s)' and upload your slides. The other fields are not editable.
- Don't forget to resubmit your proposal!
Your slides will not be made public before the Conference, but will be shared with the Conference participants in the autumn. 

Thank you for your contribution to the IGeLU 2022 Conference! If you have any questions, please address to [conference@igelu.org](mailto:conference@igelu.org).

Best regards, 

François Renaville
On behalf of the IGeLU 2022 Program Planning Committee
https://igelu.org/event/2022-annual-conference/
For your convenience, a copy of the message has been archived in your [ProposalSpace account](https://proposalspace.com/account/messages?utm_campaign=message_notice&utm_medium=email&utm_source=messaging_module).
Questions or concerns?
•	For questions about the contents of this email, please reply to the sender.
•	For questions about the proposal or the call for proposals (IGeLU 2022 Hybrid Conference and Developers' Day 12 -15th September, 2022), please contact Conference Planning Committee at [conference@igelu.org](mailto:conference@igelu.org).
•	For technical support, email [support@proposalspace.com](mailto:support@proposalspace.com) or call 877-324-3204 (+1 512-628-0330 outside the USA).
 
PO Box 302064, Austin, TX 78703-0035You've got mail
You have a new message in ProposalSpace:
From: [conference@igelu.org](mailto:conference@igelu.org)
Subject: IGeLU 2022 - Program and presentation guidelines
Dear Crystal E. Clements,

You are receiving this email because you are registered as a Presenter or Co-Presenter of a session at the IGeLU 2022 Hybrid Conference and Developers' Day. We are delighted to let you know that the Conference program has now been scheduled:

Session title: Expanding the Foundation for RDA as Linked Data: Mapping MARC21 Bibliographic to LRM/RDA/RDF
Proposal ID: 1411-85008
Date & time: Tuesday, September 13, 2022 at 4:40 PM–5:10 PM (London Time)
Location: 1. Dora Stoutzker Concert Hall	

The full program of the Conference is now available at https://mtgsked.com/p/1411/c . The Developers' Day program will be ready later.

Please note that a location has also been assigned to sessions given remotely since the audience will be composed of physical and virtual participants.

We have prepared some presentation guidelines that hopefully will be helpful to you:
https://drive.google.com/drive/folders/1USZyQQhgkq0yozckq3CGsXcwAE-AqScQ?usp=sharing

We would be happy if you could upload your slides on ProposalSpace before September 6th, 2022. To upload your presentation:
- Go to https://proposalspace.com/ from Monday August 22 and sign in.
- At your dashboard, scroll to the section titled 'Proposals'.
- Locate your session and edit it (your session will be available for edit from August 22).
- Scroll down until section 'Presentation file(s)' and upload your slides. The other fields are not editable.
- Don't forget to resubmit your proposal!
Your slides will not be made public before the Conference, but will be shared with the Conference participants in the autumn. 

Thank you for your contribution to the IGeLU 2022 Conference! If you have any questions, please address to [conference@igelu.org](mailto:conference@igelu.org).

Best regards, 

François Renaville
On behalf of the IGeLU 2022 Program Planning Committee
https://igelu.org/event/2022-annual-conference/
For your convenience, a copy of the message has been archived in your [ProposalSpace account](https://proposalspace.com/account/messages?utm_campaign=message_notice&utm_medium=email&utm_source=messaging_module).
Questions or concerns?
•	For questions about the contents of this email, please reply to the sender.
•	For questions about the proposal or the call for proposals (IGeLU 2022 Hybrid Conference and Developers' Day 12 -15th September, 2022), please contact Conference Planning Committee at [conference@igelu.org](mailto:conference@igelu.org).
•	For technical support, email [support@proposalspace.com](mailto:support@proposalspace.com) or call 877-324-3204 (+1 512-628-0330 outside the USA).
 
PO Box 302064, Austin, TX 78703-0035
