### ISSUE TITLE
SWIB22 Proposal

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#356]
SWIB22 - 14TH SEMANTIC WEB IN LIBRARIES CONFERENCE
28 November - 02 December 2022, online

Call for Proposals
SUBMISSION DEADLINE: 27 JUNE 2022

SWIB conference (Semantic Web in Libraries) is an annual conference, being held for the 14th time.

Due to the Covid-19 pandemic, we cannot be sure that by November travelling and meeting face-to-face will be possible for everybody in the community. Therefore, we have decided to hold SWIB22 online for the third time. This will offer everybody an opportunity to easily participate from all over the world.

Taking into account the different time zones of the participants, we plan to carry out the conference during the week of 28 November - 02 December, daily from UTC 14:00 to 16:30.

SWIB focuses on Linked Open Data (LOD) in libraries and related organizations. It is well established as an event where IT staff, developers, librarians, and researchers from all over the world meet and mingle and learn from each other. The topics of talks and workshops at SWIB revolve around opening data, linking data and creating tools and software for LOD production scenarios. These areas of focus are supplemented by presentations of research projects in applied sciences, industry applications, and LOD activities in other areas.

As usual, SWIB22 will be organized by ZBW - LEIBNIZ INFORMATION CENTRE FOR ECONOMICS and the NORTH RHINE-WESTPHALIAN LIBRARY SERVICE CENTRE (HBZ). The conference language is English.

For this SWIB rendition we adjusted the formats to the online
environment:

-   Presentations (20 minutes plus 5 q&a)
-   Practical workshops or tutorials (maximum 150 min, including
    breaks), introductory tutorials are very welcome

We appreciate proposals on the following or related topics:

Projects & Applications

-   integration of LOD into productive library applications
-   re-use of LOD (from libraries, Wikidata and other sources)
-   presenting & visualizing LOD
-   end-user environments for interaction with LOD (e.g. editing or
    annotation)
-   crowdsourcing/gamification approaches involving LOD sources
-   applications for open science

Technology (focus on Open Source software)

-   data
    transformation/integration/cleansing/enhancement/mapping/interlinking
-   data flow management
-   RDF validation
-   read/write linked data
-   providing updates & syncing data sources
-   machine learning for automatic indexing & named entity recognition
-   integration of symbolic and subsymbolic approaches

Standards & Best Practices

-   implementation of FAIR data principles
-   open web standards relevant for libraries
-   application profiles & provenance information
-   working with authorities & knowledge organization systems
-   usable APIs
-   preservation, maintenance & sustainability

Culture

-   collaboration, community building and empowerment
-   consolidating open source projects
-   awareness of Western bias, decolonialization

We are looking forward to receiving your proposals for presentations or workshops by 27 JUNE 2022. Please submit an abstract of 1000-1500 characters using our conference system https://www.conftool.org/swib22.
If you intend to present a specific software solution please include links to the source code repository and make sure it is openly licensed.

SWIB programme committee

Proposals will be reviewed by the programme committee:

-   Julia Beck (Frankfurt University Library)
-   Uldis Bojars (National Library of Latvia)
-   Nuno Freire (Europeana Foundation, Netherlands)
-   Anna Kasprzik (ZBW, Germany)
-   Huda Khan (Cornell University Library, USA)
-   Niklas Lindström (National Library of Sweden)
-   Devika Madalli (Indian Statistical Institute)
-   Joachim Neubert (ZBW, Germany - Chair)
-   Adrian Pohl (hbz, Germany - Chair)
-   Dorothea Salo (UW-Madison, USA)
-   Jodi Schneider (University of Illinois at Urbana-Champaign, USA)
-   MJ Suhonos (Ryerson University, Canada)
-   Osma Suominen (National Library of Finland)
-   Katherine Thornton (Yale University Library, USA)
-   Jakob Voß (GBV Common Library Network, Germany)

Call for satellite events

If you are interested in using the online conference infrastructure for a satellite event before or after the conference slot, let us know.

WEBSITE: http://swib.org/swib22 HASHTAG: #swib22 TWITTER: @swibcon

Take a look at previous SWIB conferences at https://swib.org/swib22/history.

Please do not hesitate to ask if you have any questions:

Adrian Pohl hbz Tel. +49-(0)221-40075235 E-mail: swib(at)hbz-nrw.de

or

Joachim Neubert ZBW Tel. +49-(0)40-42834462 E-mail: j.neubert(at)zbw.eu

**Comment by CECSpecialistI** [comment]
tabled until 2022-05-18

**Comment by CECSpecialistI** [comment]
Draft proposal available [here](https://docs.google.com/document/d/18LS5dBOOnNB4d3YSLnUtyrA49cbJeKu2fhEqDXsRMdU/edit?usp=sharing).  I will submit on June 23rd. Feedback and co-presenters are more than welcome!

**Comment by gerontakos** [comment]
I entered two alternate versions of the abstract. @CECSpecialistI  would you like to establish the final abstract and send tomorrow? If so, no need to run it by me (unless you want to) I'm sure it will be fine.

**Comment by CECSpecialistI** [comment]
Thank you Theo! I'm taking a look now and will send it to SWIB at the end of the day

**Comment by CECSpecialistI** [comment]
I think abstract 3 is clearly better than the first two, so I'll submit that one if that sounds good to you @gerontakos and @pan-zhuo

**Comment by gerontakos** [comment]
That sounds good to me, thank you.

**Comment by pan-zhuo** [comment]
Yes, it looks good to me.

**Comment by GordonDunsire** [comment]
Submission deadline was just extended to July 11 ...
