### ISSUE TITLE
$o

### ISSUE THREAD

**Issue by pan-zhuo** [uwlib-cams/MARC2RDA#364]
https://www.oclc.org/bibformats/en/7xx/76x-78x.html#subfieldo

"Numbers, codes, etc., used to identify an item when these identifiers are not appropriate for one of the more specific subfields (e.g., subfield ǂz). Item or accession numbers are examples."

Is $o only for item identifiers or both manifestation and item identifiers?

**Comment by CECSpecialistI** [comment]
@gerontakos is it clear from discussions and decisions how the transformation will treat $0 when it comes across these subfields in various MARC tags? Should this issue be closed?

**Comment by CECSpecialistI** [comment]
duplicate issue. see https://github.com/uwlib-cams/MARC2RDA/issues/341
