### ISSUE TITLE
22 length of the implementation-defined portion

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#41]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/LDR-DIR.csv

**Comment by CECSpecialistI** [comment]
@cspayne what's this? labels?

**Comment by tmqdeborah** [comment]
Leader 000/22 (Length of implementation-defined portion) is important for reading a 'raw' MARC communications record. It is not important for a MARCXML record or for transforming MARC to RDA.

For more information, see "[MARC for Library Use](https://archive.org/details/marcforlibraryus0000craw/page/32/mode/2up)", pages 34-39.
