### ISSUE TITLE
soft-deprecated properties in RDA Toolkit instructions

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#429]
https://access.rdatoolkit.org/en-US_ala-26b84eaa-054e-3c8c-8933-8760b9b2046f/p_x4p_pmp_cmb

https://access.rdatoolkit.org/en-US_ala-9d4aa3d6-02b8-3dbc-8ce2-60075153e028/div_xbw_4nd_1gb

**Comment by lake44me** [comment]
@CECSpecialistI , 
The first one is date of publication http://rdaregistry.info/Elements/m/P30011, it's not in the alignSoft2Rec file.  Did you copy the wrong link?

The second is note on publication statement http://rdaregistry.info/Elements/m/P30055 and it is soft-deprecated (to  Note on manifestation rdam:P30137)

**Comment by GordonDunsire** [comment]
For an update on the status of RDA soft-deprecated elements, see item 381 in the [minutes of the May 2023 RSC meeting](http://rda-rsc.org/sites/all/files/RSC_Minutes_373_392.pdf).

**Comment by lake44me** [comment]
I'm very happy to read that "Copyright Date" was on the soft-deprecated list by mistake and is not soft deprecated.

L

From: GordonDunsire ***@***.***>
Sent: Wednesday, May 31, 2023 4:58 AM
To: uwlib-cams/MARC2RDA ***@***.***>
Cc: Laura Akerman ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [uwlib-cams/MARC2RDA] soft-deprecated properties in RDA Toolkit instructions (Issue #429)


For an update on the status of RDA soft-deprecated elements, see item 381 in the minutes of the May 2023 RSC meeting<http://rda-rsc.org/sites/all/files/RSC_Minutes_373_392.pdf>.

-

**Comment by sarahruska** [comment]
Hi @CECSpecialistI @GordonDunsire @lake44me - I think this one can be closed out?

The [October 2023 RSC meeting minutes](https://www-rdatoolkit-org.offcampus.lib.washington.edu/sites/default/files/rsc/RSC_Minutes_413_443_Final_0.pdf), item 415, note the decision to deprecate terms is deferred to a future date. January, April, and July 2024 meeting minutes don't have this as a topic.

"Soft-deprecated Terms 
Damian Iseminger shared the findings. One of the clear outcomes of the survey was the need to publicise the soft-deprecated terms. It was clear from the survey results that the wider cataloguing community is not yet ready to deprecate the terms. He had therefore 
prepared and circulated RSC/TechnicalWG/2023/2 and asked voting RSC members to make a decision on his suggestion that any decisions to deprecate terms be deferred to a future date. The meeting agreed unanimously. "

**Comment by GordonDunsire** [comment]
@sarahruska and others: I think it can be closed out. The transform should not use soft-deprecated elements. The RSC will make a decision on removing them in the future, and there is no reason for the transform to be 'not yet ready'.

**Comment by sarahruska** [comment]
Thanks, Gordon. Tagging @cspayne @tynancuw @dchen077 for awareness on transform not using soft-deprecated elements, and closing out.
