### ISSUE TITLE
Iron out Transformation/Mapping Workflow Documentation Details

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#442]
https://github.com/uwlib-cams/MARC2RDA/wiki/Decisions-Index#iiic-transformation

**Comment by cspayne** [comment]
Updated III.C Transformation as discussed in 2024-02-08 transform meeting.

**Comment by cspayne** [comment]
@CECSpecialistI 
That's a great idea. I would say that the "code re-check" label should be added if the label is "coding-ar", "coded-ar", "coding-rip", or "coded-rip", so that we can ensure everything that needs to get checked is labelled as such.

**Comment by CECSpecialistI** [comment]
Makes sense! When I am out of my COVID stupor I will add this to the decisions index, along with an instruction for the transform coder to remove the re-check label when they're done re-checking, and announce the new workflow at the next meeting.

**Comment by sarahruska** [comment]
Status is Done, so moving this Issue to Closed. Confirmed "code re-check" decisions included in Decision Index; also added note for removing the re-check label
