### ISSUE TITLE
Transform - $6 and item-related fields

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/MARC2RDA#443]
Currently, we mint a new item for each field that indicates the existence of an item in order to prevent wrongly assuming two items are the same ([Decision I.C.1](https://github.com/uwlib-cams/MARC2RDA/wiki/Decisions-Index#ic1-rdamp30103-has-exemplar-of-manifestation)). 
For fields that indicate the existence of an item and also have a $6 subfield, we know that the associated 880 field is referring to the same object as the original field, so we don't want to mint two separate items in this instance. 

So each item template for a field should match on both the field and 880s with a $6 value of [field]-00. These fields will each have a unique item. 
Then, if the field has a $6, match to the associated 880 field *from within the template* using the occurrence number, and perform the same mapping within the template so that this field is linked to the same item.

**Comment by cspayne** [comment]
@gerontakos 
See [template for 561 in m2r-5xx.xsl](https://github.com/uwlib-cams/MARC2RDA/blob/c33f6b68654aa11cfd761742fff4fa675a66fc39/Working%20Documents/transformationCode/m2r-5xx.xsl#L173-#L232)

**Comment by cspayne** [comment]
Test input (values just for testing): 
```rdf
 <marc:datafield tag="561" ind1=" " ind2=" ">
            <marc:subfield code="3">MoMA :</marc:subfield>
            <marc:subfield code="a">This publication was part of the Library of the Printed Web, a collection founded and organized by Paul Soulellis and acquired by the MoMA Library in 2016.</marc:subfield>
            <marc:subfield code="5">NNMoMA</marc:subfield>
            <marc:subfield code="6">880-01</marc:subfield>
        </marc:datafield>
        <marc:datafield tag="880" ind1=" " ind2=" ">
            <marc:subfield code="6">561-01</marc:subfield>
            <marc:subfield code="a">This is from a linked field</marc:subfield>
        </marc:datafield>
        <marc:datafield tag="880" ind1=" " ind2=" ">
            <marc:subfield code="6">561-00</marc:subfield>
            <marc:subfield code="a">This is from an unnassociated linked field</marc:subfield>
        </marc:datafield>
```

Test output: 
```rdf
<!--MARC data begins-->
   <fake:marcfield>F561 ## $3 MoMA : $a This publication was part of the Library of the Printed Web, a collection founded and organized by Paul Soulellis and acquired by the MoMA Library in 2016. $5 NNMoMA $6 880-01</fake:marcfield>
   <!--RDA data begins-->
   <rdf:Description rdf:about="http://fakeIRI2.edu/904019193ited14e551">
      <rdaid:P40001>ited14e551</rdaid:P40001><!--rdaid:P40001 = has identifier for item-->
      <rdf:type rdf:resource="http://rdaregistry.info/Elements/c/C10003"/>
      <rdaio:P40049 rdf:resource="http://fakeIRI2.edu/904019193man"/><!--rdaio:P40049 = has manifestation exemplified-->
      <rdaio:P40161 rdf:resource="http://marc2rda.edu/fake/colMan/nnmoma"/><!--rdaio:P40161 = is holding of-->
      <rdaid:P40026>This publication was part of the Library of the Printed Web, a collection founded and organized by Paul Soulellis and acquired by the MoMA Library in 2016. (Applies to: MoMA :)</rdaid:P40026><!--rdaid:P40026 = has custodial history of item-->
      <rdaid:P40026>This is from a linked field</rdaid:P40026><!--rdaid:P40026 = has custodial history of item-->
   </rdf:Description>
   <!--MARC data begins-->
   <fake:marcfield>F880 ## $6 561-00 $a This is from an unnassociated linked field</fake:marcfield>
   <!--RDA data begins-->
   <rdf:Description rdf:about="http://fakeIRI2.edu/904019193ited14e565">
      <rdaid:P40001>ited14e565</rdaid:P40001><!--rdaid:P40001 = has identifier for item-->
      <rdf:type rdf:resource="http://rdaregistry.info/Elements/c/C10003"/>
      <rdaio:P40049 rdf:resource="http://fakeIRI2.edu/904019193man"/><!--rdaio:P40049 = has manifestation exemplified-->
      <rdaid:P40026>This is from an unnassociated linked field</rdaid:P40026><!--rdaid:P40026 = has custodial history of item-->
   </rdf:Description>
```

**Comment by CECSpecialistI** [comment]
Confirmed.

**Comment by cspayne** [comment]
Transformation guidance wiki has been updated. 

Item templates that need to be checked and updated in code: 

- [ ] 500
- [ ] 583
- [ ] 585

**Comment by cspayne** [comment]
Additional question that is relevant to how the transform is coded: If a field contains both a subfield 5 and a subfield 6, will the associated 880 field _also_ have the same subfield 5, or is it simply implied from the linked field? 

i.e. if a 500 field has `$5 wau` and a `$6 880-01`, will the 880 field also have `$5 wau`?

**Comment by cspayne** [comment]
> Additional question that is relevant to how the transform is coded: If a field contains both a subfield 5 and a subfield 6, will the associated 880 field _also_ have the same subfield 5, or is it simply implied from the linked field?
> 
> i.e. if a 500 field has `$5 wau` and a `$6 880-01`, will the 880 field also have `$5 wau`?

answer from meeting: No, the 880 may not be identical in what it holds
