### ISSUE TITLE
IFLA 2025 Proposal

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#469]
[Call for proposals](https://www.ifla.org/news/call-for-presentation-proposals-2025-metadata-standards-symposium/)

* 19 March 2025
* Deadline for submission of proposals: 29 November 2024

**Comment by szapoun** [comment]
Dear Crystal, Laura, and Ebe,
the Symposium has 3 subthemes: (“Technology Matters”, “Accessibility Matters”, or “Competencies Matters”). I think our work relates to the first subtheme. Alternatively, we could use the experience of the project to identify key competencies for metadata professionals. What do you prefer?

**Comment by CECSpecialistI** [comment]
> Dear Crystal, Laura, and Ebe, the Symposium has 3 subthemes: (“Technology Matters”, “Accessibility Matters”, or “Competencies Matters”). I think our work relates to the first subtheme. Alternatively, we could use the experience of the project to identify key competencies for metadata professionals. What do you prefer?

I agree that our work relates to the first subtheme of "Technology Matters", particularly this suggested topic of interest:
"Adapting metadata standards to emerging technologies, formats and content types"

**Comment by lake44me** [comment]
I would lean toward "Adapting metadata standards to emerging technologies, formats and content types"

...but have at least one slide that points to competencies.

A point that could be made - understanding of LRM/RDA is going to be necessary not just for metadata professionals, but those that build, revise and update our discovery systems, which should do more to adapt to the different data models than just "turn it into MARC"...
________________________________
From: Crystal Yragui ***@***.***>
Sent: Thursday, October 31, 2024 10:56 AM
To: uwlib-cams/MARC2RDA ***@***.***>
Cc: Laura Akerman ***@***.***>; Assign ***@***.***>
Subject: [External] Re: [uwlib-cams/MARC2RDA] IFLA 2025 Proposal (Issue #469)


Dear Crystal, Laura, and Ebe, the Symposium has 3 subthemes: (“Technology Matters”, “Accessibility Matters”, or “Competencies Matters”). I think our work relates to the first subtheme. Alternatively, we could use the experience of the project to identify key competencies for metadata professionals. What do you prefer?

I agree that our work relates to the first subtheme of "Technology Matters", particularly this suggested topic of interest:
"Adapting metadata standards to emerging technologies, formats and content types"

**Comment by szapoun** [comment]
Dear Crystal, Laura, and Ebe
I suppose we will present the project and Phase 1, right? If so, we need description of project, key milestones, phase 1 description, and some important findings during the process: e.g., different semantics between MARC21 and RDA, but also problems arising from local/legacy cataloguing policies, we could also refer to technical difficulties, like the one Cypress referred yesterday (LC cutting off access to API if many queries are done in a short time -- I hope I understood it correctly). 

I propose (in order to get hings going) first decide on the bullets/issues that we will focus on. Afterwards we can find the proper title :)

**Comment by CECSpecialistI** [comment]
I agree with you Sofia. I think we can focus on the "technology matters" subtopic and touch on the others, and build out our abstract first and then the title. I've started us a Google Doc with some pertinent information to get us going [here](https://docs.google.com/document/d/1MUAQqQXbUIy6ppNtUHDCwTqKGBIRHZnSthWOrnsEdM0/edit?usp=sharing)

**Comment by CECSpecialistI** [comment]
I put in some ideas that I feel connect our project to the symposium/IFLA's mission specifically [here](https://docs.google.com/document/d/1MUAQqQXbUIy6ppNtUHDCwTqKGBIRHZnSthWOrnsEdM0/edit?tab=t.0#bookmark=id.mqdyjqtxdc1v)
