### ISSUE TITLE
020 International standard book number

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#57]

**Comment by cspayne** [comment]
@AdamSchiff @szapoun @CECSpecialistI 
Are there cases where an 020 field has linked 880 field? I couldn't find any, but do we need to account for this possibility in the transform? 
All of the examples I found for 880s were `$6 020-00`.

**Comment by CECSpecialistI** [comment]
I don't think we need to account for this.

**Comment by AdamSchiff** [comment]
I don't think ISBNs are issued in anything other than Arabic numerals.  I don't know about qualifiers, but in records where 040 $b = eng, I would expect any qualifiers to be in English or at least in Latin script.  However, I expect that agencies that have a non-Latin script language of cataloging would include non-Latin terms in 020 $q.  But they probably wouldn't have a paired field with the same ISBN and $q in Latin.

So... I think it would be extremely rare to have 020 paired with an 880.

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________

**Comment by AdamSchiff** [comment]
P.S.  I talked with a Korean cataloger and a Japanese cataloger here and they don't use paired 020s.

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________
