### ISSUE TITLE
026 fingerprint identifier

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#61]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/0XX.csv

**Comment by cspayne** [comment]
@lake44me If we are minting a nomen for the fingerprint identifier, can we really add the subfield labels to the nomen string?
Should we instead use $e as the nomen string if it is present, and otherwise use the combined values of $a, $b, $c, and $d?

**Comment by lake44me** [comment]
@cspayne you have a point and I really should have paid more attention when reviewing.  I have taken $e out of the mapping for a, b, c, d,, and $2 as a nomen string and source of nomen.   I specified a concatenated nomen string for abcd, but to keep the labeling that's in the MARC I added a note on nomen.  I added a mapping for $e as a fingerprint nomen (so we can have source).  Does that take care of it?
