### ISSUE TITLE
027 standard technical report number

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#62]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/0XX.csv

**Comment by cspayne** [comment]
@lake44me It looks like you reviewed and approved this mapping, but the Google Sheet still indicates 'first pass' in column A. Is everything here reviewed and ready to transform? Thanks!

**Comment by cspayne** [comment]
Great! Thanks.

**Comment by lake44me** [comment]
@cspayne  I'm sosorry, but I didn't look closely enough at these mappings before putting a "reviewed" on them.

I should have added the same kind of modification to Zhuo's transform notes to all of the mappings, but I only did it on the first one.   I think I expected Pan Zhuo to update the other transform notes, but he left before doing that.  I happened to pick this one as an example for a presentation I'm giving.  
Do you see what I mean, and did this negatively affect your coding?

In any case, I will update the mapping...
Let me know if this isn't clear...  I think the changes came out of an "Identifiers" discussion somewhere.  --Laura

**Comment by cspayne** [comment]
@lake44me 
Do you mean that the other rows (rows 2- 5) should also mint a nomen the way that the first row does? 
Updating the code won't be too much work, but I want to be sure that I understand how we are mapping this before making any changes.

**Comment by lake44me** [comment]
You can find the background on this in the Decisions index https://github.com/uwlib-cams/MARC2RDA/wiki/Decisions-Index#iin-identifiers and even more at The Creating Identifiers discussion #375 https://github.com/uwlib-cams/MARC2RDA/discussions/375.  Yes, I believe all of the mapping rows need to follow the minting nomens appoach.  Sorry I missed updating all the rows - I had a lot to deal with as you will see.   I suppose someone should check everything on the list in that discussion now, just don't know when I will find time to do it.   There were some things in that discussion that I don't believe we went forward with (custom datatypes?) but I think the minting nomens approach is solid.

**Comment by cspayne** [comment]
Thank you Laura! 
I've updated the 027 mapping sheet so a nomen is minted for each identifier and will update the code as well

**Comment by lake44me** [comment]
Thanks so much @cspayne !  The transform notes look good and I can cross this off my to-do list.
