### ISSUE TITLE
028 publisher number or distributor number

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#63]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/0XX.csv

**Comment by lake44me** [comment]
@SitaKB  Hi Sita, I changed a lot about the mapping on this tag, will you review and change First Pass to @reviewed?  Or fix anything that needs fixing?  Thanks.

**Comment by SitaKB** [comment]
@lake44me Hi Lauren, It looks good. I have changed 'First Pass' to 'reviewed'. Thank you

**Comment by lake44me** [comment]
@SitaKB @cspayne the value of ind3 is "Other music publisher number".  I'm thinking we didn't find that to be useful information as a category, so didn't map it.   "music publisher number" is expressed in the property so it doesn't need to be a category.
