### ISSUE TITLE
085 synthesized classification number components

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#97]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/0XX.csv

**Comment by pennylenger** [comment]
@GordonDunsire Hi Gordon, this 085 Synthesized Classification Number Components is not included in your document. Can it be mapped using the same approach? if differently, how? It has many synthesized components. Thank you for your help.

**Comment by GordonDunsire** [comment]
@pennylenger: the MARC 21 manual indicates that this field duplicates the classification number recorded in fields 082 and 083, so it does not need to be transformed. In any case, we are interested in the actual classification number that is assigned to the work, but we are not interested in how it is synthesized from simpler components.

Can @CECSpecialistI check that my assumption is correct? There are no records with 085 but no 082 or 083?

**Comment by sarahruska** [comment]
Status is Done, so moving this Issue to Closed. Add 085 to Not Mapped section of Decision Index
