### ISSUE TITLE
088 report number

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#99]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/0XX.csv

**Comment by lake44me** [comment]
@pan-zhuo Hi, I'm reviewing this mapping.  I am not sure for this identifier (and maybe for others!) for manifestation element, that adding a prefix "Report number:" is allowed.   I know we have used this approach with note types, but identifiers are different.  Have you checked this with Adam?  Recording Unstructured and Structured description are not allowed, only Identifier and IRI.  RDA allows for adding specific amendments, sometimes specified to be at the end of the identifier (current practice, but the style is not specified - usually parentheses are used).   LC-PCC says to apply the guideline, "Indicate that an identifier is incorrect, cancelled, or invalid, as appropriate." The LC-PCC guidelines say "use judgment in applying the recording method", which might include adding amendments (or not).  

I think this might be worthy of discussion (unless I missed it!) - is it important to pass the specific tag "type of identifier" through to RDA/RDF from MARC and **if so**, what's the appropriate way to do it?  RDA has not seen fit to provide us with specific identifier types, except for publisher number and plate number for notated music.

@AdamSchiff @SitaKB @CECSpecialistI @GordonDunsire @szapoun
